const FOOD_DATABASE = [
  // ── PROTEINS ───────────────────────────────────────────────
  { id: 1, name: "Chicken Breast (cooked)", cal: 165, protein: 31, carbs: 0, fat: 3.6, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 2, name: "Salmon Fillet", cal: 208, protein: 20, carbs: 0, fat: 13, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 3, name: "Tuna (canned in water)", cal: 109, protein: 25, carbs: 0, fat: 0.5, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 4, name: "Egg (large)", cal: 78, protein: 6, carbs: 0.6, fat: 5, fiber: 0, sugar: 0.6, serving: 1, unit: "large", category: "protein" },
  { id: 5, name: "Greek Yogurt (plain)", cal: 59, protein: 10, carbs: 3.6, fat: 0.4, fiber: 0, sugar: 3.2, serving: 100, unit: "g", category: "dairy" },
  { id: 6, name: "Cottage Cheese (low fat)", cal: 81, protein: 11, carbs: 3.4, fat: 2.3, fiber: 0, sugar: 2.7, serving: 100, unit: "g", category: "dairy" },
  { id: 7, name: "Beef (lean ground)", cal: 215, protein: 26, carbs: 0, fat: 12, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 8, name: "Turkey Breast", cal: 135, protein: 30, carbs: 0, fat: 1, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 9, name: "Tofu (firm)", cal: 76, protein: 8, carbs: 1.9, fat: 4.8, fiber: 0.3, sugar: 0.5, serving: 100, unit: "g", category: "protein" },
  { id: 10, name: "Shrimp", cal: 99, protein: 24, carbs: 0.2, fat: 0.3, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 11, name: "Tilapia", cal: 96, protein: 20, carbs: 0, fat: 2, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 12, name: "Whey Protein Shake", cal: 120, protein: 25, carbs: 3, fat: 1.5, fiber: 0, sugar: 2, serving: 1, unit: "scoop", category: "protein" },
  { id: 13, name: "Black Beans (cooked)", cal: 132, protein: 9, carbs: 24, fat: 0.5, fiber: 8, sugar: 0.3, serving: 100, unit: "g", category: "legumes" },
  { id: 14, name: "Lentils (cooked)", cal: 116, protein: 9, carbs: 20, fat: 0.4, fiber: 8, sugar: 1.8, serving: 100, unit: "g", category: "legumes" },
  { id: 15, name: "Chickpeas (cooked)", cal: 164, protein: 9, carbs: 27, fat: 2.6, fiber: 8, sugar: 4.8, serving: 100, unit: "g", category: "legumes" },
  // ── GRAINS ─────────────────────────────────────────────────
  { id: 16, name: "White Rice (cooked)", cal: 130, protein: 2.7, carbs: 28, fat: 0.3, fiber: 0.4, sugar: 0, serving: 100, unit: "g", category: "grains" },
  { id: 17, name: "Brown Rice (cooked)", cal: 112, protein: 2.6, carbs: 23, fat: 0.9, fiber: 1.8, sugar: 0, serving: 100, unit: "g", category: "grains" },
  { id: 18, name: "Oatmeal (cooked)", cal: 71, protein: 2.5, carbs: 12, fat: 1.5, fiber: 1.7, sugar: 0, serving: 100, unit: "g", category: "grains" },
  { id: 19, name: "Whole Wheat Bread", cal: 247, protein: 13, carbs: 41, fat: 4, fiber: 7, sugar: 5, serving: 100, unit: "g", category: "grains" },
  { id: 20, name: "White Bread", cal: 265, protein: 9, carbs: 49, fat: 3.2, fiber: 2.7, sugar: 5, serving: 100, unit: "g", category: "grains" },
  { id: 21, name: "Pasta (cooked)", cal: 131, protein: 5, carbs: 25, fat: 1.1, fiber: 1.8, sugar: 0.6, serving: 100, unit: "g", category: "grains" },
  { id: 22, name: "Quinoa (cooked)", cal: 120, protein: 4.4, carbs: 21, fat: 1.9, fiber: 2.8, sugar: 0.9, serving: 100, unit: "g", category: "grains" },
  { id: 23, name: "Sweet Potato (baked)", cal: 90, protein: 2, carbs: 21, fat: 0.1, fiber: 3.3, sugar: 6.5, serving: 100, unit: "g", category: "grains" },
  { id: 24, name: "White Potato (baked)", cal: 93, protein: 2.5, carbs: 21, fat: 0.1, fiber: 2.1, sugar: 1.1, serving: 100, unit: "g", category: "grains" },
  { id: 25, name: "Tortilla (flour, medium)", cal: 146, protein: 4, carbs: 25, fat: 3.5, fiber: 1.5, sugar: 0.5, serving: 1, unit: "piece", category: "grains" },
  // ── VEGETABLES ─────────────────────────────────────────────
  { id: 26, name: "Broccoli", cal: 34, protein: 2.8, carbs: 7, fat: 0.4, fiber: 2.6, sugar: 1.7, serving: 100, unit: "g", category: "vegetables" },
  { id: 27, name: "Spinach", cal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, fiber: 2.2, sugar: 0.4, serving: 100, unit: "g", category: "vegetables" },
  { id: 28, name: "Kale", cal: 49, protein: 4.3, carbs: 9, fat: 0.9, fiber: 3.6, sugar: 2.3, serving: 100, unit: "g", category: "vegetables" },
  { id: 29, name: "Bell Pepper (red)", cal: 31, protein: 1, carbs: 6, fat: 0.3, fiber: 2.1, sugar: 4.2, serving: 100, unit: "g", category: "vegetables" },
  { id: 30, name: "Cucumber", cal: 16, protein: 0.7, carbs: 3.6, fat: 0.1, fiber: 0.5, sugar: 1.7, serving: 100, unit: "g", category: "vegetables" },
  { id: 31, name: "Tomato", cal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, fiber: 1.2, sugar: 2.6, serving: 100, unit: "g", category: "vegetables" },
  { id: 32, name: "Carrot", cal: 41, protein: 0.9, carbs: 10, fat: 0.2, fiber: 2.8, sugar: 4.7, serving: 100, unit: "g", category: "vegetables" },
  { id: 33, name: "Zucchini", cal: 17, protein: 1.2, carbs: 3.1, fat: 0.3, fiber: 1, sugar: 2.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 34, name: "Mushrooms", cal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "vegetables" },
  { id: 35, name: "Asparagus", cal: 20, protein: 2.2, carbs: 3.7, fat: 0.1, fiber: 2.1, sugar: 1.9, serving: 100, unit: "g", category: "vegetables" },
  // ── FRUITS ─────────────────────────────────────────────────
  { id: 36, name: "Banana (medium)", cal: 89, protein: 1.1, carbs: 23, fat: 0.3, fiber: 2.6, sugar: 12, serving: 1, unit: "medium", category: "fruits" },
  { id: 37, name: "Apple (medium)", cal: 72, protein: 0.4, carbs: 19, fat: 0.2, fiber: 3.4, sugar: 14, serving: 1, unit: "medium", category: "fruits" },
  { id: 38, name: "Blueberries", cal: 57, protein: 0.7, carbs: 14, fat: 0.3, fiber: 2.4, sugar: 10, serving: 100, unit: "g", category: "fruits" },
  { id: 39, name: "Strawberries", cal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, fiber: 2, sugar: 4.9, serving: 100, unit: "g", category: "fruits" },
  { id: 40, name: "Orange (medium)", cal: 62, protein: 1.2, carbs: 15, fat: 0.2, fiber: 3.1, sugar: 12, serving: 1, unit: "medium", category: "fruits" },
  { id: 41, name: "Avocado (half)", cal: 120, protein: 1.5, carbs: 6.4, fat: 11, fiber: 5, sugar: 0.5, serving: 1, unit: "half", category: "fruits" },
  { id: 42, name: "Mango", cal: 60, protein: 0.8, carbs: 15, fat: 0.4, fiber: 1.6, sugar: 14, serving: 100, unit: "g", category: "fruits" },
  { id: 43, name: "Grapes", cal: 69, protein: 0.7, carbs: 18, fat: 0.2, fiber: 0.9, sugar: 15, serving: 100, unit: "g", category: "fruits" },
  // ── DAIRY & FATS ───────────────────────────────────────────
  { id: 44, name: "Whole Milk", cal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 4.8, serving: 100, unit: "ml", category: "dairy" },
  { id: 45, name: "Skim Milk", cal: 35, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, sugar: 5, serving: 100, unit: "ml", category: "dairy" },
  { id: 46, name: "Cheddar Cheese", cal: 403, protein: 25, carbs: 1.3, fat: 33, fiber: 0, sugar: 0.5, serving: 100, unit: "g", category: "dairy" },
  { id: 47, name: "Mozzarella", cal: 280, protein: 28, carbs: 3.1, fat: 17, fiber: 0, sugar: 1.2, serving: 100, unit: "g", category: "dairy" },
  { id: 48, name: "Butter", cal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sugar: 0.1, serving: 100, unit: "g", category: "fats" },
  { id: 49, name: "Olive Oil", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 50, name: "Almonds", cal: 579, protein: 21, carbs: 22, fat: 50, fiber: 12.5, sugar: 4.4, serving: 100, unit: "g", category: "nuts" },
  { id: 51, name: "Peanut Butter", cal: 588, protein: 25, carbs: 20, fat: 50, fiber: 6, sugar: 9, serving: 100, unit: "g", category: "nuts" },
  { id: 52, name: "Walnuts", cal: 654, protein: 15, carbs: 14, fat: 65, fiber: 6.7, sugar: 2.6, serving: 100, unit: "g", category: "nuts" },
  { id: 53, name: "Cashews", cal: 553, protein: 18, carbs: 30, fat: 44, fiber: 3.3, sugar: 5.9, serving: 100, unit: "g", category: "nuts" },
  // ── FAST FOOD ──────────────────────────────────────────────
  { id: 54, name: "McDonald's Big Mac", cal: 563, protein: 26, carbs: 45, fat: 33, fiber: 3, sugar: 9, serving: 1, unit: "burger", category: "fast food" },
  { id: 55, name: "Pizza (cheese, 1 slice)", cal: 272, protein: 12, carbs: 33, fat: 10, fiber: 2.3, sugar: 3.6, serving: 1, unit: "slice", category: "fast food" },
  { id: 56, name: "Potato Chips", cal: 536, protein: 7, carbs: 53, fat: 35, fiber: 4.4, sugar: 0.5, serving: 100, unit: "g", category: "snacks" },
  { id: 57, name: "Dark Chocolate (85%)", cal: 598, protein: 8, carbs: 46, fat: 43, fiber: 10, sugar: 24, serving: 100, unit: "g", category: "snacks" },
  { id: 58, name: "Granola Bar", cal: 193, protein: 4, carbs: 29, fat: 7.6, fiber: 1.5, sugar: 12, serving: 1, unit: "bar", category: "snacks" },
  { id: 59, name: "Rice Cakes (plain)", cal: 387, protein: 8, carbs: 82, fat: 3, fiber: 2, sugar: 0, serving: 100, unit: "g", category: "snacks" },
  { id: 60, name: "Hummus", cal: 166, protein: 8, carbs: 14, fat: 10, fiber: 6, sugar: 0.3, serving: 100, unit: "g", category: "snacks" },
  { id: 61, name: "Orange Juice", cal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 8.4, serving: 100, unit: "ml", category: "beverages" },
  { id: 62, name: "Coffee (black)", cal: 2, protein: 0.3, carbs: 0, fat: 0, fiber: 0, sugar: 0, serving: 240, unit: "ml", category: "beverages" },
  { id: 63, name: "Latte (whole milk)", cal: 190, protein: 10, carbs: 19, fat: 7, fiber: 0, sugar: 18, serving: 360, unit: "ml", category: "beverages" },
  { id: 64, name: "Protein Bar (Quest)", cal: 200, protein: 21, carbs: 22, fat: 8, fiber: 14, sugar: 1, serving: 1, unit: "bar", category: "snacks" },
  { id: 65, name: "Smoothie (banana + protein)", cal: 280, protein: 22, carbs: 38, fat: 3, fiber: 3, sugar: 18, serving: 400, unit: "ml", category: "beverages" },
  { id: 66, name: "Oat Milk", cal: 47, protein: 1.3, carbs: 6.8, fat: 1.4, fiber: 1, sugar: 4.1, serving: 100, unit: "ml", category: "dairy" },
  { id: 67, name: "Almond Milk (unsweetened)", cal: 17, protein: 0.4, carbs: 0.3, fat: 1.4, fiber: 0.5, sugar: 0, serving: 100, unit: "ml", category: "dairy" },
  { id: 68, name: "Edamame", cal: 121, protein: 11, carbs: 10, fat: 5, fiber: 5.2, sugar: 2.2, serving: 100, unit: "g", category: "legumes" },
  { id: 69, name: "Pork Tenderloin", cal: 143, protein: 26, carbs: 0, fat: 3.5, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 70, name: "Kidney Beans (canned)", cal: 127, protein: 8.7, carbs: 22.8, fat: 0.5, fiber: 6.4, sugar: 0.3, serving: 100, unit: "g", category: "legumes" },
  { id: 71, name: "Sushi Roll (California, 8pc)", cal: 250, protein: 9, carbs: 38, fat: 7, fiber: 1, sugar: 4, serving: 1, unit: "roll", category: "japanese" },
  { id: 72, name: "Caesar Salad (large)", cal: 480, protein: 10, carbs: 26, fat: 40, fiber: 3, sugar: 4, serving: 1, unit: "serving", category: "fast food" },
  { id: 73, name: "Steak (sirloin)", cal: 207, protein: 26, carbs: 0, fat: 11, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 74, name: "Chia Seeds", cal: 486, protein: 17, carbs: 42, fat: 31, fiber: 34, sugar: 0, serving: 100, unit: "g", category: "nuts" },
  { id: 75, name: "Honey", cal: 304, protein: 0.3, carbs: 82, fat: 0, fiber: 0.2, sugar: 82, serving: 100, unit: "g", category: "snacks" },
  { id: 76, name: "Corn (sweet, cooked)", cal: 86, protein: 3.3, carbs: 19, fat: 1.4, fiber: 2.7, sugar: 3.2, serving: 100, unit: "g", category: "vegetables" },
  { id: 77, name: "Watermelon", cal: 30, protein: 0.6, carbs: 7.6, fat: 0.2, fiber: 0.4, sugar: 6.2, serving: 100, unit: "g", category: "fruits" },
  { id: 78, name: "Pineapple", cal: 50, protein: 0.5, carbs: 13, fat: 0.1, fiber: 1.4, sugar: 10, serving: 100, unit: "g", category: "fruits" },
  { id: 79, name: "Cream Cheese", cal: 350, protein: 6, carbs: 4, fat: 35, fiber: 0, sugar: 3.2, serving: 100, unit: "g", category: "dairy" },
  { id: 80, name: "Maple Syrup", cal: 260, protein: 0, carbs: 67, fat: 0.1, fiber: 0, sugar: 60, serving: 100, unit: "ml", category: "snacks" },
  { id: 81, name: "Green Tea", cal: 1, protein: 0.2, carbs: 0.2, fat: 0, fiber: 0, sugar: 0, serving: 240, unit: "ml", category: "beverages" },
  { id: 82, name: "Flaxseeds", cal: 534, protein: 18, carbs: 29, fat: 42, fiber: 27, sugar: 1.5, serving: 100, unit: "g", category: "nuts" },
  { id: 83, name: "Mixed Nuts", cal: 607, protein: 20, carbs: 22, fat: 54, fiber: 6, sugar: 4.4, serving: 100, unit: "g", category: "nuts" },
  { id: 84, name: "Tempeh", cal: 193, protein: 19, carbs: 9.4, fat: 11, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 85, name: "Seitan", cal: 370, protein: 75, carbs: 14, fat: 1.9, fiber: 0.6, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 86, name: "Sour Cream", cal: 193, protein: 2.4, carbs: 4.6, fat: 19, fiber: 0, sugar: 4.1, serving: 100, unit: "g", category: "dairy" },
  { id: 87, name: "Peas (frozen, cooked)", cal: 81, protein: 5.4, carbs: 14, fat: 0.4, fiber: 5.1, sugar: 5.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 88, name: "Cod Fish", cal: 82, protein: 18, carbs: 0, fat: 0.7, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "protein" },
  { id: 89, name: "Lemon", cal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, fiber: 2.8, sugar: 2.5, serving: 100, unit: "g", category: "fruits" },
  { id: 90, name: "Yogurt (plain full fat)", cal: 97, protein: 5.7, carbs: 7.9, fat: 5, fiber: 0, sugar: 7.9, serving: 100, unit: "g", category: "dairy" },

  // ══════════════════════════════════════════════════════════
  // 🇵🇰 PAKISTANI FOODS
  // ══════════════════════════════════════════════════════════
  { id: 91, name: "Chicken Biryani", cal: 392, protein: 25, carbs: 45, fat: 11, fiber: 1.5, sugar: 2, serving: 250, unit: "g", category: "pakistani" },
  { id: 92, name: "Beef Biryani", cal: 420, protein: 24, carbs: 44, fat: 14, fiber: 1.2, sugar: 2, serving: 250, unit: "g", category: "pakistani" },
  { id: 93, name: "Nihari (beef stew)", cal: 285, protein: 22, carbs: 8, fat: 19, fiber: 0.5, sugar: 1, serving: 200, unit: "g", category: "pakistani" },
  { id: 94, name: "Halwa Puri (full plate)", cal: 650, protein: 12, carbs: 85, fat: 28, fiber: 3, sugar: 12, serving: 1, unit: "plate", category: "pakistani" },
  { id: 95, name: "Puri", cal: 200, protein: 4, carbs: 25, fat: 10, fiber: 1, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 96, name: "Suji Halwa", cal: 280, protein: 5, carbs: 38, fat: 12, fiber: 0.5, sugar: 18, serving: 100, unit: "g", category: "pakistani" },
  { id: 97, name: "Dal Makhani", cal: 130, protein: 5, carbs: 15, fat: 5.5, fiber: 4, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 98, name: "Masoor Dal (red lentil)", cal: 93, protein: 7, carbs: 15, fat: 0.5, fiber: 4, sugar: 0.5, serving: 100, unit: "g", category: "pakistani" },
  { id: 99, name: "Chicken Karahi", cal: 155, protein: 14, carbs: 2.5, fat: 9.5, fiber: 0.5, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 100, name: "Mutton Karahi", cal: 175, protein: 13, carbs: 2, fat: 12.5, fiber: 0.3, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 101, name: "Chapati / Roti", cal: 120, protein: 4, carbs: 23, fat: 2, fiber: 2.5, sugar: 0.2, serving: 1, unit: "medium", category: "pakistani" },
  { id: 102, name: "Naan", cal: 260, protein: 9, carbs: 45, fat: 5, fiber: 2, sugar: 2, serving: 1, unit: "piece", category: "pakistani" },
  { id: 103, name: "Plain Paratha", cal: 260, protein: 6, carbs: 33, fat: 12, fiber: 2, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 104, name: "Aloo Paratha", cal: 318, protein: 7, carbs: 46, fat: 12, fiber: 2.5, sugar: 1, serving: 1, unit: "piece", category: "pakistani" },
  { id: 105, name: "Saag (mustard greens)", cal: 98, protein: 4, carbs: 10, fat: 5, fiber: 3, sugar: 2, serving: 100, unit: "g", category: "pakistani" },
  { id: 106, name: "Palak Gosht", cal: 140, protein: 11, carbs: 4, fat: 9, fiber: 1.5, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 107, name: "Seekh Kebab", cal: 130, protein: 12, carbs: 4, fat: 8, fiber: 0.3, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 108, name: "Shami Kebab", cal: 115, protein: 10, carbs: 7, fat: 6, fiber: 1, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 109, name: "Boti Kebab", cal: 110, protein: 12, carbs: 1, fat: 7, fiber: 0.2, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 110, name: "Chicken Tikka", cal: 140, protein: 16, carbs: 2, fat: 7, fiber: 0.2, sugar: 1, serving: 1, unit: "piece", category: "pakistani" },
  { id: 111, name: "Samosa", cal: 150, protein: 4, carbs: 18, fat: 7, fiber: 1, sugar: 0.5, serving: 1, unit: "piece", category: "pakistani" },
  { id: 112, name: "Pakora (mixed veg)", cal: 245, protein: 8, carbs: 25, fat: 13, fiber: 2, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 113, name: "Chana Chaat", cal: 195, protein: 8, carbs: 30, fat: 5, fiber: 5, sugar: 3, serving: 150, unit: "g", category: "pakistani" },
  { id: 114, name: "Dahi Bhalla", cal: 210, protein: 8, carbs: 28, fat: 8, fiber: 2, sugar: 8, serving: 150, unit: "g", category: "pakistani" },
  { id: 115, name: "Sweet Lassi", cal: 210, protein: 7, carbs: 32, fat: 5, fiber: 0, sugar: 28, serving: 300, unit: "ml", category: "pakistani" },
  { id: 116, name: "Salted Lassi", cal: 135, protein: 7, carbs: 12, fat: 7, fiber: 0, sugar: 8, serving: 300, unit: "ml", category: "pakistani" },
  { id: 117, name: "Kheer", cal: 140, protein: 4, carbs: 22, fat: 4.5, fiber: 0.2, sugar: 16, serving: 100, unit: "g", category: "pakistani" },
  { id: 118, name: "Zarda (sweet rice)", cal: 285, protein: 4, carbs: 55, fat: 6, fiber: 0.3, sugar: 28, serving: 100, unit: "g", category: "pakistani" },
  { id: 119, name: "Gulab Jamun", cal: 143, protein: 2, carbs: 24, fat: 5, fiber: 0.2, sugar: 18, serving: 1, unit: "piece", category: "pakistani" },
  { id: 120, name: "Jalebi", cal: 310, protein: 3, carbs: 55, fat: 9, fiber: 0.2, sugar: 35, serving: 100, unit: "g", category: "pakistani" },
  { id: 121, name: "Barfi (milk sweet)", cal: 130, protein: 3, carbs: 17, fat: 6, fiber: 0, sugar: 14, serving: 1, unit: "piece", category: "pakistani" },
  { id: 122, name: "Kulfi", cal: 150, protein: 4, carbs: 20, fat: 7, fiber: 0, sugar: 18, serving: 90, unit: "ml", category: "pakistani" },
  { id: 123, name: "Gol Gappa / Pani Puri (6pcs)", cal: 195, protein: 4, carbs: 32, fat: 6, fiber: 2, sugar: 3, serving: 6, unit: "pieces", category: "pakistani" },
  { id: 124, name: "Paya (trotters)", cal: 180, protein: 18, carbs: 2, fat: 11, fiber: 0, sugar: 0.5, serving: 200, unit: "g", category: "pakistani" },
  { id: 125, name: "Chicken Korma", cal: 175, protein: 15, carbs: 6, fat: 10, fiber: 0.5, sugar: 2, serving: 100, unit: "g", category: "pakistani" },
  { id: 126, name: "Mutton Korma", cal: 205, protein: 13, carbs: 6, fat: 15, fiber: 0.5, sugar: 2, serving: 100, unit: "g", category: "pakistani" },
  { id: 127, name: "Sheer Khurma", cal: 185, protein: 5, carbs: 25, fat: 7, fiber: 0.5, sugar: 18, serving: 150, unit: "ml", category: "pakistani" },
  { id: 128, name: "Aloo Gosht (potato + meat)", cal: 155, protein: 10, carbs: 12, fat: 8, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 129, name: "Bhuna Gosht", cal: 190, protein: 14, carbs: 3, fat: 13, fiber: 0.3, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 130, name: "Sindhi Biryani", cal: 405, protein: 24, carbs: 47, fat: 12, fiber: 1.5, sugar: 2, serving: 250, unit: "g", category: "pakistani" },
  { id: 131, name: "Kabuli Pulao", cal: 350, protein: 18, carbs: 48, fat: 9, fiber: 2, sugar: 3, serving: 250, unit: "g", category: "pakistani" },
  { id: 132, name: "Chai (Pakistani milk tea)", cal: 55, protein: 2, carbs: 8, fat: 2, fiber: 0, sugar: 6, serving: 200, unit: "ml", category: "pakistani" },
  { id: 133, name: "Rabri", cal: 195, protein: 6, carbs: 22, fat: 9, fiber: 0, sugar: 18, serving: 100, unit: "g", category: "pakistani" },
  { id: 134, name: "Sohan Halwa", cal: 380, protein: 4, carbs: 60, fat: 15, fiber: 0.5, sugar: 45, serving: 100, unit: "g", category: "pakistani" },
  { id: 135, name: "Keema (minced meat)", cal: 220, protein: 18, carbs: 5, fat: 14, fiber: 0.5, sugar: 1.5, serving: 100, unit: "g", category: "pakistani" },
  { id: 136, name: "Dahi Puri", cal: 195, protein: 6, carbs: 30, fat: 6, fiber: 2, sugar: 6, serving: 150, unit: "g", category: "pakistani" },
  { id: 137, name: "Chicken Handi", cal: 160, protein: 14, carbs: 5, fat: 9.5, fiber: 0.5, sugar: 1.5, serving: 100, unit: "g", category: "pakistani" },
  { id: 138, name: "Mutton Biryani", cal: 430, protein: 22, carbs: 46, fat: 16, fiber: 1.2, sugar: 2, serving: 250, unit: "g", category: "pakistani" },

  // ══════════════════════════════════════════════════════════
  // 🇮🇳 INDIAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 139, name: "Butter Chicken (Murgh Makhani)", cal: 148, protein: 12, carbs: 5, fat: 8.5, fiber: 0.5, sugar: 3, serving: 100, unit: "g", category: "indian" },
  { id: 140, name: "Paneer Butter Masala", cal: 170, protein: 7, carbs: 7, fat: 12.5, fiber: 0.5, sugar: 3, serving: 100, unit: "g", category: "indian" },
  { id: 141, name: "Dal Tadka", cal: 105, protein: 5.5, carbs: 14, fat: 3, fiber: 4, sugar: 1, serving: 100, unit: "g", category: "indian" },
  { id: 142, name: "Palak Paneer", cal: 148, protein: 6, carbs: 6, fat: 10.5, fiber: 1.5, sugar: 1.5, serving: 100, unit: "g", category: "indian" },
  { id: 143, name: "Rajma (red kidney beans)", cal: 100, protein: 5, carbs: 15, fat: 1.5, fiber: 4.5, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 144, name: "Chole (chickpea curry)", cal: 110, protein: 5, carbs: 14, fat: 3.5, fiber: 4, sugar: 1, serving: 100, unit: "g", category: "indian" },
  { id: 145, name: "Aloo Gobi", cal: 63, protein: 2, carbs: 10, fat: 1.5, fiber: 2, sugar: 2, serving: 100, unit: "g", category: "indian" },
  { id: 146, name: "Matar Paneer", cal: 120, protein: 6, carbs: 8, fat: 7.5, fiber: 2, sugar: 2, serving: 100, unit: "g", category: "indian" },
  { id: 147, name: "Idli (2 pieces)", cal: 132, protein: 4, carbs: 28, fat: 0.5, fiber: 1, sugar: 0.5, serving: 2, unit: "pieces", category: "indian" },
  { id: 148, name: "Plain Dosa", cal: 173, protein: 5, carbs: 32, fat: 3, fiber: 1, sugar: 0.5, serving: 1, unit: "piece", category: "indian" },
  { id: 149, name: "Masala Dosa", cal: 380, protein: 8, carbs: 60, fat: 11, fiber: 2.5, sugar: 1.5, serving: 1, unit: "large", category: "indian" },
  { id: 150, name: "Sambar", cal: 53, protein: 2.5, carbs: 7, fat: 1.5, fiber: 2, sugar: 2, serving: 100, unit: "ml", category: "indian" },
  { id: 151, name: "Pav Bhaji", cal: 420, protein: 9, carbs: 65, fat: 14, fiber: 3, sugar: 5, serving: 1, unit: "serving", category: "indian" },
  { id: 152, name: "Vada Pav", cal: 295, protein: 6, carbs: 45, fat: 10, fiber: 2, sugar: 4, serving: 1, unit: "piece", category: "indian" },
  { id: 153, name: "Tandoori Chicken", cal: 105, protein: 16, carbs: 2, fat: 4, fiber: 0.2, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 154, name: "Malai Kofta", cal: 190, protein: 6, carbs: 10, fat: 14, fiber: 0.5, sugar: 2, serving: 100, unit: "g", category: "indian" },
  { id: 155, name: "Shahi Paneer", cal: 185, protein: 8, carbs: 8, fat: 14, fiber: 0.5, sugar: 3, serving: 100, unit: "g", category: "indian" },
  { id: 156, name: "Raita", cal: 55, protein: 2.5, carbs: 5.5, fat: 2.5, fiber: 0.3, sugar: 4, serving: 100, unit: "g", category: "indian" },
  { id: 157, name: "Khichdi", cal: 98, protein: 4, carbs: 16, fat: 1.5, fiber: 1.5, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 158, name: "Poha", cal: 131, protein: 2.5, carbs: 24, fat: 2.5, fiber: 0.5, sugar: 1, serving: 100, unit: "g", category: "indian" },
  { id: 159, name: "Dhokla", cal: 152, protein: 7, carbs: 27, fat: 3, fiber: 1.5, sugar: 2, serving: 100, unit: "g", category: "indian" },
  { id: 160, name: "Thepla", cal: 165, protein: 5, carbs: 24, fat: 6, fiber: 2, sugar: 0.5, serving: 1, unit: "piece", category: "indian" },
  { id: 161, name: "Bhelpuri", cal: 158, protein: 4, carbs: 30, fat: 4, fiber: 2, sugar: 3, serving: 150, unit: "g", category: "indian" },
  { id: 162, name: "Papdi Chaat", cal: 245, protein: 6, carbs: 38, fat: 8, fiber: 2.5, sugar: 8, serving: 150, unit: "g", category: "indian" },
  { id: 163, name: "Amritsari Kulcha", cal: 305, protein: 8, carbs: 48, fat: 10, fiber: 2, sugar: 2, serving: 1, unit: "piece", category: "indian" },
  { id: 164, name: "Mango Lassi", cal: 165, protein: 5, carbs: 28, fat: 4, fiber: 0.5, sugar: 24, serving: 300, unit: "ml", category: "indian" },
  { id: 165, name: "Nimbu Pani (lemonade)", cal: 48, protein: 0.2, carbs: 12, fat: 0.1, fiber: 0.1, sugar: 10, serving: 250, unit: "ml", category: "indian" },
  { id: 166, name: "Masala Chai", cal: 60, protein: 2, carbs: 9, fat: 2, fiber: 0, sugar: 7, serving: 200, unit: "ml", category: "indian" },
  { id: 167, name: "Upma", cal: 120, protein: 3, carbs: 20, fat: 3.5, fiber: 1, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 168, name: "Vada (medu)", cal: 175, protein: 5, carbs: 18, fat: 9, fiber: 2, sugar: 0.5, serving: 1, unit: "piece", category: "indian" },
  { id: 169, name: "Kachori", cal: 280, protein: 6, carbs: 32, fat: 14, fiber: 2, sugar: 1, serving: 1, unit: "piece", category: "indian" },
  { id: 170, name: "Hyderabadi Biryani", cal: 415, protein: 26, carbs: 46, fat: 13, fiber: 1.5, sugar: 2, serving: 250, unit: "g", category: "indian" },
  { id: 171, name: "Filter Coffee (South Indian)", cal: 65, protein: 2.5, carbs: 8, fat: 2.5, fiber: 0, sugar: 7, serving: 150, unit: "ml", category: "indian" },
  { id: 172, name: "Haleem", cal: 160, protein: 14, carbs: 12, fat: 6, fiber: 2, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 173, name: "Rava Kesari", cal: 250, protein: 4, carbs: 42, fat: 8, fiber: 0.5, sugar: 28, serving: 100, unit: "g", category: "indian" },
  { id: 174, name: "Gajar Ka Halwa", cal: 240, protein: 4, carbs: 34, fat: 10, fiber: 1, sugar: 26, serving: 100, unit: "g", category: "indian" },
  { id: 175, name: "Pulao (veg rice)", cal: 170, protein: 4, carbs: 32, fat: 3.5, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "indian" },

  // ══════════════════════════════════════════════════════════
  // 🌍 MIDDLE EASTERN / ARABIC FOODS
  // ══════════════════════════════════════════════════════════
  { id: 176, name: "Chicken Shawarma (wrap)", cal: 380, protein: 25, carbs: 40, fat: 12, fiber: 2, sugar: 3, serving: 1, unit: "wrap", category: "arabic" },
  { id: 177, name: "Meat Shawarma (wrap)", cal: 420, protein: 22, carbs: 42, fat: 15, fiber: 2, sugar: 3, serving: 1, unit: "wrap", category: "arabic" },
  { id: 178, name: "Falafel (4 pieces)", cal: 220, protein: 9, carbs: 24, fat: 11, fiber: 5, sugar: 1, serving: 4, unit: "pieces", category: "arabic" },
  { id: 179, name: "Tabbouleh", cal: 69, protein: 2, carbs: 8, fat: 4, fiber: 2, sugar: 1.5, serving: 100, unit: "g", category: "arabic" },
  { id: 180, name: "Fattoush Salad", cal: 70, protein: 1.5, carbs: 9, fat: 3.5, fiber: 1.5, sugar: 2, serving: 100, unit: "g", category: "arabic" },
  { id: 181, name: "Kofta Kebab", cal: 155, protein: 13, carbs: 4, fat: 10, fiber: 0.3, sugar: 1, serving: 1, unit: "skewer", category: "arabic" },
  { id: 182, name: "Mansaf (lamb & rice)", cal: 520, protein: 28, carbs: 55, fat: 20, fiber: 1, sugar: 2, serving: 1, unit: "serving", category: "arabic" },
  { id: 183, name: "Kabsa (Saudi rice dish)", cal: 480, protein: 28, carbs: 52, fat: 16, fiber: 1.5, sugar: 2, serving: 1, unit: "serving", category: "arabic" },
  { id: 184, name: "Mandi", cal: 460, protein: 26, carbs: 50, fat: 15, fiber: 1, sugar: 1.5, serving: 1, unit: "serving", category: "arabic" },
  { id: 185, name: "Kibbeh (1 piece)", cal: 100, protein: 7, carbs: 7, fat: 5, fiber: 0.5, sugar: 0.5, serving: 1, unit: "piece", category: "arabic" },
  { id: 186, name: "Baklava (1 piece)", cal: 145, protein: 3, carbs: 16, fat: 8, fiber: 0.5, sugar: 10, serving: 1, unit: "piece", category: "arabic" },
  { id: 187, name: "Knafeh", cal: 380, protein: 8, carbs: 50, fat: 17, fiber: 0.5, sugar: 28, serving: 100, unit: "g", category: "arabic" },
  { id: 188, name: "Maqluba", cal: 310, protein: 18, carbs: 38, fat: 10, fiber: 1.5, sugar: 1.5, serving: 200, unit: "g", category: "arabic" },
  { id: 189, name: "Musakhan (Palestinian)", cal: 490, protein: 28, carbs: 42, fat: 22, fiber: 2.5, sugar: 3, serving: 1, unit: "serving", category: "arabic" },
  { id: 190, name: "Fatteh", cal: 295, protein: 12, carbs: 32, fat: 13, fiber: 3, sugar: 4, serving: 200, unit: "g", category: "arabic" },
  { id: 191, name: "Arabic Bread (pita)", cal: 275, protein: 9, carbs: 55, fat: 1, fiber: 2, sugar: 0.5, serving: 100, unit: "g", category: "arabic" },
  { id: 192, name: "Karak Chai", cal: 85, protein: 3, carbs: 11, fat: 3, fiber: 0, sugar: 9, serving: 200, unit: "ml", category: "arabic" },
  { id: 193, name: "Luqaimat (sweet dumplings)", cal: 290, protein: 5, carbs: 42, fat: 12, fiber: 0.5, sugar: 18, serving: 100, unit: "g", category: "arabic" },
  { id: 194, name: "Mehalabia (milk pudding)", cal: 145, protein: 4, carbs: 22, fat: 4.5, fiber: 0, sugar: 18, serving: 150, unit: "g", category: "arabic" },
  { id: 195, name: "Shakshuka", cal: 130, protein: 8, carbs: 8, fat: 7, fiber: 2, sugar: 5, serving: 200, unit: "g", category: "arabic" },

  // ══════════════════════════════════════════════════════════
  // 🇨🇳 CHINESE FOODS
  // ══════════════════════════════════════════════════════════
  { id: 196, name: "Vegetable Fried Rice", cal: 123, protein: 2.5, carbs: 23, fat: 3, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "chinese" },
  { id: 197, name: "Chicken Fried Rice", cal: 150, protein: 7.5, carbs: 22, fat: 4, fiber: 0.8, sugar: 1, serving: 100, unit: "g", category: "chinese" },
  { id: 198, name: "Chow Mein", cal: 146, protein: 6, carbs: 19, fat: 5, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "chinese" },
  { id: 199, name: "Kung Pao Chicken", cal: 135, protein: 10, carbs: 8, fat: 7, fiber: 0.8, sugar: 3, serving: 100, unit: "g", category: "chinese" },
  { id: 200, name: "Sweet & Sour Pork", cal: 140, protein: 8, carbs: 15, fat: 5.5, fiber: 0.5, sugar: 8, serving: 100, unit: "g", category: "chinese" },
  { id: 201, name: "Steamed Dumplings (4pcs)", cal: 190, protein: 9, carbs: 26, fat: 6, fiber: 1, sugar: 1, serving: 4, unit: "pieces", category: "chinese" },
  { id: 202, name: "Spring Roll (fried)", cal: 120, protein: 3, carbs: 16, fat: 6, fiber: 0.8, sugar: 1, serving: 1, unit: "piece", category: "chinese" },
  { id: 203, name: "Wonton Soup", cal: 140, protein: 8, carbs: 18, fat: 4, fiber: 0.5, sugar: 1, serving: 300, unit: "ml", category: "chinese" },
  { id: 204, name: "Egg Drop Soup", cal: 80, protein: 6, carbs: 8, fat: 2, fiber: 0.2, sugar: 0.5, serving: 300, unit: "ml", category: "chinese" },
  { id: 205, name: "Mapo Tofu", cal: 80, protein: 4.5, carbs: 4, fat: 5, fiber: 0.5, sugar: 0.5, serving: 100, unit: "g", category: "chinese" },
  { id: 206, name: "Peking Duck", cal: 337, protein: 19, carbs: 4, fat: 28, fiber: 0, sugar: 2, serving: 100, unit: "g", category: "chinese" },
  { id: 207, name: "Hot & Sour Soup", cal: 70, protein: 4, carbs: 9, fat: 2, fiber: 0.5, sugar: 1, serving: 300, unit: "ml", category: "chinese" },
  { id: 208, name: "Lo Mein (chicken)", cal: 165, protein: 8, carbs: 24, fat: 4.5, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "chinese" },
  { id: 209, name: "General Tso's Chicken", cal: 185, protein: 13, carbs: 18, fat: 7, fiber: 0.5, sugar: 8, serving: 100, unit: "g", category: "chinese" },
  { id: 210, name: "Dim Sum (har gow, 3pcs)", cal: 130, protein: 7, carbs: 16, fat: 4, fiber: 0.5, sugar: 0.5, serving: 3, unit: "pieces", category: "chinese" },
  { id: 211, name: "Bok Choy (cooked)", cal: 21, protein: 2.5, carbs: 3, fat: 0.3, fiber: 1.7, sugar: 1.5, serving: 100, unit: "g", category: "chinese" },

  // ══════════════════════════════════════════════════════════
  // 🇯🇵 JAPANESE FOODS
  // ══════════════════════════════════════════════════════════
  { id: 212, name: "Tuna Nigiri (2pcs)", cal: 130, protein: 10, carbs: 18, fat: 1, fiber: 0.2, sugar: 2, serving: 2, unit: "pieces", category: "japanese" },
  { id: 213, name: "Salmon Nigiri (2pcs)", cal: 140, protein: 9, carbs: 18, fat: 2, fiber: 0.2, sugar: 2, serving: 2, unit: "pieces", category: "japanese" },
  { id: 214, name: "Tonkotsu Ramen (1 bowl)", cal: 510, protein: 26, carbs: 66, fat: 14, fiber: 2, sugar: 4, serving: 1, unit: "bowl", category: "japanese" },
  { id: 215, name: "Miso Soup", cal: 40, protein: 3, carbs: 4, fat: 1, fiber: 0.5, sugar: 0.5, serving: 250, unit: "ml", category: "japanese" },
  { id: 216, name: "Tempura (4 pieces)", cal: 280, protein: 8, carbs: 30, fat: 14, fiber: 0.5, sugar: 1, serving: 4, unit: "pieces", category: "japanese" },
  { id: 217, name: "Teriyaki Chicken", cal: 148, protein: 17, carbs: 6, fat: 5, fiber: 0.2, sugar: 4, serving: 100, unit: "g", category: "japanese" },
  { id: 218, name: "Gyoza (5 pieces)", cal: 220, protein: 11, carbs: 25, fat: 8, fiber: 1, sugar: 1, serving: 5, unit: "pieces", category: "japanese" },
  { id: 219, name: "Onigiri (rice ball)", cal: 185, protein: 5, carbs: 38, fat: 1, fiber: 0.5, sugar: 0.5, serving: 1, unit: "piece", category: "japanese" },
  { id: 220, name: "Katsu Curry (bowl)", cal: 615, protein: 28, carbs: 70, fat: 24, fiber: 3, sugar: 8, serving: 1, unit: "bowl", category: "japanese" },
  { id: 221, name: "Tonkatsu (pork cutlet)", cal: 280, protein: 22, carbs: 14, fat: 15, fiber: 0.5, sugar: 0.5, serving: 100, unit: "g", category: "japanese" },
  { id: 222, name: "Mochi (1 piece)", cal: 95, protein: 1, carbs: 22, fat: 0.5, fiber: 0.2, sugar: 8, serving: 1, unit: "piece", category: "japanese" },
  { id: 223, name: "Matcha Latte", cal: 130, protein: 5, carbs: 18, fat: 4, fiber: 0.5, sugar: 15, serving: 300, unit: "ml", category: "japanese" },
  { id: 224, name: "Soba Noodles (cooked)", cal: 99, protein: 5, carbs: 21, fat: 0.1, fiber: 0.5, sugar: 0.3, serving: 100, unit: "g", category: "japanese" },
  { id: 225, name: "Udon Noodles (cooked)", cal: 96, protein: 3, carbs: 20, fat: 0.5, fiber: 0.2, sugar: 0.2, serving: 100, unit: "g", category: "japanese" },

  // ══════════════════════════════════════════════════════════
  // 🇰🇷 KOREAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 226, name: "Bibimbap (1 bowl)", cal: 560, protein: 22, carbs: 74, fat: 16, fiber: 4, sugar: 5, serving: 1, unit: "bowl", category: "korean" },
  { id: 227, name: "Kimchi", cal: 15, protein: 1, carbs: 3, fat: 0.1, fiber: 1.2, sugar: 1, serving: 100, unit: "g", category: "korean" },
  { id: 228, name: "Bulgogi (beef)", cal: 145, protein: 13, carbs: 8, fat: 6, fiber: 0.3, sugar: 5, serving: 100, unit: "g", category: "korean" },
  { id: 229, name: "Tteokbokki (rice cakes)", cal: 148, protein: 4, carbs: 26, fat: 3, fiber: 0.5, sugar: 5, serving: 100, unit: "g", category: "korean" },
  { id: 230, name: "Korean Fried Chicken (3pcs)", cal: 380, protein: 24, carbs: 28, fat: 18, fiber: 0.5, sugar: 3, serving: 3, unit: "pieces", category: "korean" },
  { id: 231, name: "Japchae (glass noodles)", cal: 140, protein: 4.5, carbs: 19, fat: 5, fiber: 1, sugar: 3, serving: 100, unit: "g", category: "korean" },
  { id: 232, name: "Samgyeopsal (pork belly)", cal: 280, protein: 17, carbs: 0, fat: 24, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "korean" },
  { id: 233, name: "Korean Ramyeon (1 pack)", cal: 380, protein: 9, carbs: 55, fat: 14, fiber: 1, sugar: 4, serving: 1, unit: "pack", category: "korean" },
  { id: 234, name: "Sundubu Jjigae (soft tofu stew)", cal: 90, protein: 7, carbs: 5, fat: 4, fiber: 1, sugar: 1, serving: 200, unit: "g", category: "korean" },
  { id: 235, name: "Doenjang Jjigae (soybean stew)", cal: 80, protein: 5, carbs: 6, fat: 3.5, fiber: 1.5, sugar: 1, serving: 200, unit: "g", category: "korean" },

  // ══════════════════════════════════════════════════════════
  // 🇲🇽 MEXICAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 236, name: "Chicken Burrito", cal: 580, protein: 30, carbs: 75, fat: 15, fiber: 5, sugar: 4, serving: 1, unit: "burrito", category: "mexican" },
  { id: 237, name: "Chicken Taco", cal: 190, protein: 14, carbs: 20, fat: 7, fiber: 1.5, sugar: 1.5, serving: 1, unit: "taco", category: "mexican" },
  { id: 238, name: "Nachos with Cheese", cal: 480, protein: 10, carbs: 55, fat: 26, fiber: 3, sugar: 2, serving: 150, unit: "g", category: "mexican" },
  { id: 239, name: "Guacamole", cal: 160, protein: 2, carbs: 9, fat: 14, fiber: 5, sugar: 0.5, serving: 100, unit: "g", category: "mexican" },
  { id: 240, name: "Cheese Quesadilla", cal: 400, protein: 18, carbs: 38, fat: 18, fiber: 2, sugar: 2, serving: 1, unit: "serving", category: "mexican" },
  { id: 241, name: "Churros", cal: 370, protein: 6, carbs: 49, fat: 18, fiber: 1, sugar: 14, serving: 100, unit: "g", category: "mexican" },
  { id: 242, name: "Enchiladas (2 pieces)", cal: 420, protein: 20, carbs: 38, fat: 20, fiber: 3, sugar: 4, serving: 2, unit: "pieces", category: "mexican" },
  { id: 243, name: "Horchata", cal: 120, protein: 1, carbs: 27, fat: 2, fiber: 0, sugar: 22, serving: 240, unit: "ml", category: "mexican" },
  { id: 244, name: "Refried Beans", cal: 110, protein: 6, carbs: 18, fat: 2.5, fiber: 6, sugar: 0.5, serving: 100, unit: "g", category: "mexican" },

  // ══════════════════════════════════════════════════════════
  // 🇮🇹 ITALIAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 245, name: "Spaghetti Bolognese", cal: 149, protein: 7.5, carbs: 17, fat: 5, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "italian" },
  { id: 246, name: "Pasta Carbonara", cal: 166, protein: 7, carbs: 17, fat: 7.5, fiber: 0.8, sugar: 0.5, serving: 100, unit: "g", category: "italian" },
  { id: 247, name: "Lasagna", cal: 157, protein: 8.5, carbs: 14, fat: 7, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "italian" },
  { id: 248, name: "Margherita Pizza (1 slice)", cal: 235, protein: 10, carbs: 30, fat: 8, fiber: 1.5, sugar: 3, serving: 1, unit: "slice", category: "italian" },
  { id: 249, name: "Tiramisu", cal: 197, protein: 4, carbs: 19, fat: 11, fiber: 0.2, sugar: 14, serving: 100, unit: "g", category: "italian" },
  { id: 250, name: "Risotto (mushroom)", cal: 152, protein: 4, carbs: 25, fat: 4, fiber: 0.5, sugar: 1, serving: 100, unit: "g", category: "italian" },
  { id: 251, name: "Gnocchi", cal: 170, protein: 4, carbs: 35, fat: 1, fiber: 1, sugar: 0.5, serving: 100, unit: "g", category: "italian" },
  { id: 252, name: "Minestrone Soup", cal: 52, protein: 2.5, carbs: 9, fat: 1, fiber: 2, sugar: 2, serving: 200, unit: "ml", category: "italian" },
  { id: 253, name: "Bruschetta (2 pieces)", cal: 200, protein: 5, carbs: 30, fat: 7, fiber: 2, sugar: 2, serving: 2, unit: "pieces", category: "italian" },
  { id: 254, name: "Cannoli", cal: 255, protein: 5, carbs: 24, fat: 15, fiber: 0.5, sugar: 14, serving: 1, unit: "piece", category: "italian" },
  { id: 255, name: "Focaccia Bread", cal: 260, protein: 7, carbs: 42, fat: 8, fiber: 2, sugar: 1, serving: 100, unit: "g", category: "italian" },

  // ══════════════════════════════════════════════════════════
  // 🇹🇷 TURKISH FOODS
  // ══════════════════════════════════════════════════════════
  { id: 256, name: "Doner Kebab (wrap)", cal: 450, protein: 25, carbs: 45, fat: 18, fiber: 2, sugar: 3, serving: 1, unit: "wrap", category: "turkish" },
  { id: 257, name: "Lahmacun", cal: 195, protein: 9, carbs: 24, fat: 7, fiber: 1.5, sugar: 2, serving: 1, unit: "piece", category: "turkish" },
  { id: 258, name: "Cheese Börek", cal: 360, protein: 12, carbs: 30, fat: 22, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "turkish" },
  { id: 259, name: "Menemen (egg dish)", cal: 98, protein: 5, carbs: 5, fat: 6, fiber: 1, sugar: 3, serving: 100, unit: "g", category: "turkish" },
  { id: 260, name: "Pide (cheese)", cal: 240, protein: 10, carbs: 28, fat: 10, fiber: 1, sugar: 2, serving: 200, unit: "g", category: "turkish" },
  { id: 261, name: "Ayran", cal: 70, protein: 4, carbs: 5, fat: 4, fiber: 0, sugar: 4, serving: 250, unit: "ml", category: "turkish" },
  { id: 262, name: "Turkish Delight", cal: 350, protein: 0.5, carbs: 85, fat: 0.5, fiber: 0.5, sugar: 70, serving: 100, unit: "g", category: "turkish" },
  { id: 263, name: "Turkish Tea (1 cup)", cal: 0, protein: 0, carbs: 0, fat: 0, fiber: 0, sugar: 0, serving: 150, unit: "ml", category: "turkish" },
  { id: 264, name: "Iskender Kebab", cal: 280, protein: 20, carbs: 18, fat: 14, fiber: 1, sugar: 2, serving: 200, unit: "g", category: "turkish" },
  { id: 265, name: "Gözleme (cheese & spinach)", cal: 265, protein: 9, carbs: 32, fat: 11, fiber: 1.5, sugar: 1, serving: 1, unit: "piece", category: "turkish" },

  // ══════════════════════════════════════════════════════════
  // 🌍 AFRICAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 266, name: "Jollof Rice (West African)", cal: 155, protein: 3, carbs: 29, fat: 3.5, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "african" },
  { id: 267, name: "Suya (Nigerian grilled beef)", cal: 210, protein: 26, carbs: 5, fat: 10, fiber: 0.5, sugar: 1, serving: 100, unit: "g", category: "african" },
  { id: 268, name: "Injera", cal: 100, protein: 3, carbs: 20, fat: 0.5, fiber: 1.5, sugar: 0.2, serving: 1, unit: "piece", category: "african" },
  { id: 269, name: "Couscous (cooked)", cal: 112, protein: 4, carbs: 23, fat: 0.2, fiber: 1.4, sugar: 0.1, serving: 100, unit: "g", category: "african" },
  { id: 270, name: "Fried Plantain", cal: 192, protein: 1, carbs: 40, fat: 6, fiber: 2, sugar: 16, serving: 100, unit: "g", category: "african" },
  { id: 271, name: "Moroccan Lamb Tagine", cal: 175, protein: 14, carbs: 10, fat: 9, fiber: 2, sugar: 4, serving: 200, unit: "g", category: "african" },
  { id: 272, name: "Egusi Soup", cal: 210, protein: 10, carbs: 8, fat: 16, fiber: 2, sugar: 1, serving: 200, unit: "g", category: "african" },
  { id: 273, name: "Doro Wat (Ethiopian chicken stew)", cal: 145, protein: 12, carbs: 6, fat: 8, fiber: 1, sugar: 2, serving: 200, unit: "g", category: "african" },
  { id: 274, name: "Fufu", cal: 330, protein: 2, carbs: 80, fat: 0.5, fiber: 1, sugar: 1, serving: 250, unit: "g", category: "african" },
  { id: 275, name: "Akara (bean fritters)", cal: 210, protein: 9, carbs: 22, fat: 10, fiber: 3, sugar: 1, serving: 100, unit: "g", category: "african" },

  // ══════════════════════════════════════════════════════════
  // 🇺🇸 AMERICAN / WESTERN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 276, name: "Pancakes (3 stack)", cal: 370, protein: 9, carbs: 56, fat: 13, fiber: 1.5, sugar: 12, serving: 3, unit: "pancakes", category: "american" },
  { id: 277, name: "Waffle (large)", cal: 300, protein: 8, carbs: 43, fat: 12, fiber: 1, sugar: 8, serving: 1, unit: "waffle", category: "american" },
  { id: 278, name: "Hot Dog", cal: 290, protein: 11, carbs: 24, fat: 17, fiber: 1, sugar: 5, serving: 1, unit: "hot dog", category: "american" },
  { id: 279, name: "Mac and Cheese", cal: 148, protein: 6, carbs: 19, fat: 5, fiber: 0.5, sugar: 2, serving: 100, unit: "g", category: "american" },
  { id: 280, name: "BBQ Ribs", cal: 290, protein: 22, carbs: 10, fat: 18, fiber: 0.2, sugar: 8, serving: 100, unit: "g", category: "american" },
  { id: 281, name: "Coleslaw", cal: 130, protein: 1, carbs: 14, fat: 8, fiber: 1.5, sugar: 8, serving: 100, unit: "g", category: "american" },
  { id: 282, name: "Buffalo Wings (6pcs)", cal: 425, protein: 36, carbs: 6, fat: 28, fiber: 0.2, sugar: 1, serving: 6, unit: "pieces", category: "american" },
  { id: 283, name: "Chocolate Milkshake", cal: 475, protein: 11, carbs: 65, fat: 20, fiber: 1, sugar: 58, serving: 400, unit: "ml", category: "american" },
  { id: 284, name: "Apple Pie (1 slice)", cal: 295, protein: 3, carbs: 43, fat: 13, fiber: 2, sugar: 22, serving: 1, unit: "slice", category: "american" },
  { id: 285, name: "Cheesecake (1 slice)", cal: 401, protein: 7, carbs: 37, fat: 26, fiber: 0.5, sugar: 26, serving: 1, unit: "slice", category: "american" },
  { id: 286, name: "Brownie", cal: 227, protein: 3, carbs: 35, fat: 10, fiber: 1.5, sugar: 22, serving: 1, unit: "piece", category: "american" },
  { id: 287, name: "Blueberry Muffin", cal: 377, protein: 5, carbs: 55, fat: 15, fiber: 1.5, sugar: 28, serving: 1, unit: "muffin", category: "american" },
  { id: 288, name: "Bagel (plain)", cal: 245, protein: 10, carbs: 48, fat: 1.5, fiber: 2, sugar: 5, serving: 1, unit: "bagel", category: "american" },
  { id: 289, name: "Club Sandwich", cal: 590, protein: 32, carbs: 52, fat: 26, fiber: 3, sugar: 6, serving: 1, unit: "sandwich", category: "american" },
  { id: 290, name: "Clam Chowder", cal: 165, protein: 9, carbs: 18, fat: 6.5, fiber: 0.5, sugar: 2, serving: 250, unit: "ml", category: "american" },

  // ══════════════════════════════════════════════════════════
  // 🇬🇧 BRITISH / EUROPEAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 291, name: "Fish and Chips", cal: 834, protein: 38, carbs: 91, fat: 36, fiber: 4, sugar: 1, serving: 1, unit: "serving", category: "british" },
  { id: 292, name: "Shepherd's Pie", cal: 127, protein: 7, carbs: 13, fat: 4.5, fiber: 1.5, sugar: 1.5, serving: 100, unit: "g", category: "british" },
  { id: 293, name: "Croissant", cal: 406, protein: 7.5, carbs: 46, fat: 21, fiber: 2, sugar: 10, serving: 100, unit: "g", category: "french" },
  { id: 294, name: "Crepe (plain)", cal: 80, protein: 3, carbs: 11, fat: 3, fiber: 0.3, sugar: 1, serving: 1, unit: "piece", category: "french" },
  { id: 295, name: "French Onion Soup", cal: 110, protein: 6, carbs: 14, fat: 4, fiber: 1, sugar: 4, serving: 300, unit: "ml", category: "french" },
  { id: 296, name: "Schnitzel", cal: 190, protein: 16, carbs: 9, fat: 9, fiber: 0.5, sugar: 0.3, serving: 100, unit: "g", category: "european" },
  { id: 297, name: "Pretzel (large)", cal: 385, protein: 11, carbs: 80, fat: 4, fiber: 3, sugar: 3, serving: 1, unit: "pretzel", category: "european" },
  { id: 298, name: "Pierogi (5pcs)", cal: 295, protein: 9, carbs: 45, fat: 9, fiber: 2, sugar: 2, serving: 5, unit: "pieces", category: "european" },
  { id: 299, name: "Borscht (Russian beet soup)", cal: 68, protein: 2, carbs: 12, fat: 1.5, fiber: 2, sugar: 6, serving: 250, unit: "ml", category: "european" },
  { id: 300, name: "Baguette (French bread)", cal: 270, protein: 9, carbs: 55, fat: 1.5, fiber: 2.5, sugar: 1, serving: 100, unit: "g", category: "french" },

  // ══════════════════════════════════════════════════════════
  // 🌏 SOUTHEAST ASIAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 301, name: "Pad Thai", cal: 163, protein: 7.5, carbs: 20, fat: 6, fiber: 1, sugar: 3, serving: 100, unit: "g", category: "thai" },
  { id: 302, name: "Tom Yum Soup", cal: 30, protein: 2.5, carbs: 3, fat: 1, fiber: 0.5, sugar: 1, serving: 100, unit: "ml", category: "thai" },
  { id: 303, name: "Nasi Goreng (Indonesian)", cal: 127, protein: 5, carbs: 18, fat: 4, fiber: 0.8, sugar: 1.5, serving: 100, unit: "g", category: "indonesian" },
  { id: 304, name: "Chicken Satay (4 skewers)", cal: 225, protein: 20, carbs: 8, fat: 12, fiber: 0.5, sugar: 3, serving: 4, unit: "skewers", category: "indonesian" },
  { id: 305, name: "Beef Rendang", cal: 175, protein: 12, carbs: 4, fat: 12.5, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "indonesian" },
  { id: 306, name: "Hainanese Chicken Rice", cal: 470, protein: 28, carbs: 58, fat: 12, fiber: 1, sugar: 2, serving: 1, unit: "bowl", category: "singaporean" },
  { id: 307, name: "Pho (Vietnamese noodle soup)", cal: 420, protein: 25, carbs: 60, fat: 8, fiber: 2, sugar: 3, serving: 1, unit: "bowl", category: "vietnamese" },
  { id: 308, name: "Banh Mi (Vietnamese sandwich)", cal: 440, protein: 22, carbs: 55, fat: 14, fiber: 2.5, sugar: 4, serving: 1, unit: "sandwich", category: "vietnamese" },
  { id: 309, name: "Mango Sticky Rice", cal: 215, protein: 3, carbs: 44, fat: 4, fiber: 1.5, sugar: 22, serving: 200, unit: "g", category: "thai" },
  { id: 310, name: "Laksa (coconut noodle soup)", cal: 195, protein: 10, carbs: 20, fat: 8, fiber: 1.5, sugar: 2, serving: 300, unit: "ml", category: "singaporean" },
  { id: 311, name: "Mee Goreng (fried noodles)", cal: 148, protein: 6, carbs: 22, fat: 4.5, fiber: 1, sugar: 3, serving: 100, unit: "g", category: "indonesian" },
  { id: 312, name: "Green Curry (Thai)", cal: 140, protein: 10, carbs: 8, fat: 8, fiber: 1, sugar: 3, serving: 200, unit: "g", category: "thai" },
  { id: 313, name: "Spring Rolls (Vietnamese, fresh)", cal: 100, protein: 5, carbs: 16, fat: 2, fiber: 1, sugar: 2, serving: 1, unit: "roll", category: "vietnamese" },

  // ══════════════════════════════════════════════════════════
  // 🥤 PROCESSED & PACKAGED FOODS
  // ══════════════════════════════════════════════════════════
  { id: 314, name: "Lays Classic (original)", cal: 536, protein: 7, carbs: 52, fat: 34, fiber: 4.4, sugar: 0.5, serving: 100, unit: "g", category: "processed" },
  { id: 315, name: "Lays BBQ Chips", cal: 524, protein: 7, carbs: 54, fat: 32, fiber: 4, sugar: 2, serving: 100, unit: "g", category: "processed" },
  { id: 316, name: "Lays Salt & Vinegar", cal: 530, protein: 7, carbs: 53, fat: 33, fiber: 4, sugar: 1, serving: 100, unit: "g", category: "processed" },
  { id: 317, name: "Doritos Nacho Cheese", cal: 484, protein: 7, carbs: 63, fat: 23, fiber: 4, sugar: 2, serving: 100, unit: "g", category: "processed" },
  { id: 318, name: "Doritos Cool Ranch", cal: 490, protein: 6, carbs: 60, fat: 25, fiber: 4, sugar: 2, serving: 100, unit: "g", category: "processed" },
  { id: 319, name: "Pringles Original", cal: 544, protein: 4, carbs: 52, fat: 35, fiber: 1, sugar: 1.5, serving: 100, unit: "g", category: "processed" },
  { id: 320, name: "Cheetos Puffs", cal: 535, protein: 7, carbs: 56, fat: 32, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "processed" },
  { id: 321, name: "Oreo Cookies", cal: 471, protein: 5, carbs: 67, fat: 21, fiber: 1.8, sugar: 36, serving: 100, unit: "g", category: "processed" },
  { id: 322, name: "Digestive Biscuits", cal: 463, protein: 7, carbs: 65, fat: 20, fiber: 2.5, sugar: 16, serving: 100, unit: "g", category: "processed" },
  { id: 323, name: "Marie Biscuits", cal: 412, protein: 8, carbs: 74, fat: 10, fiber: 1.5, sugar: 20, serving: 100, unit: "g", category: "processed" },
  { id: 324, name: "Parle-G Biscuits", cal: 461, protein: 7, carbs: 74, fat: 15, fiber: 0.5, sugar: 18, serving: 100, unit: "g", category: "processed" },
  { id: 325, name: "Coca-Cola (355ml can)", cal: 140, protein: 0, carbs: 39, fat: 0, fiber: 0, sugar: 39, serving: 355, unit: "ml", category: "processed" },
  { id: 326, name: "Pepsi (355ml can)", cal: 150, protein: 0, carbs: 41, fat: 0, fiber: 0, sugar: 41, serving: 355, unit: "ml", category: "processed" },
  { id: 327, name: "Sprite (355ml can)", cal: 140, protein: 0, carbs: 38, fat: 0, fiber: 0, sugar: 38, serving: 355, unit: "ml", category: "processed" },
  { id: 328, name: "Mountain Dew (355ml can)", cal: 170, protein: 0, carbs: 46, fat: 0, fiber: 0, sugar: 46, serving: 355, unit: "ml", category: "processed" },
  { id: 329, name: "7-Up (355ml can)", cal: 140, protein: 0, carbs: 38, fat: 0, fiber: 0, sugar: 38, serving: 355, unit: "ml", category: "processed" },
  { id: 330, name: "Fanta Orange (355ml)", cal: 155, protein: 0, carbs: 42, fat: 0, fiber: 0, sugar: 42, serving: 355, unit: "ml", category: "processed" },
  { id: 331, name: "Red Bull Energy (250ml)", cal: 112, protein: 1, carbs: 28, fat: 0, fiber: 0, sugar: 27, serving: 250, unit: "ml", category: "processed" },
  { id: 332, name: "Monster Energy (473ml)", cal: 210, protein: 2, carbs: 54, fat: 0, fiber: 0, sugar: 54, serving: 473, unit: "ml", category: "processed" },
  { id: 333, name: "KitKat (45g bar)", cal: 218, protein: 3, carbs: 27, fat: 11, fiber: 0.5, sugar: 22, serving: 1, unit: "bar", category: "processed" },
  { id: 334, name: "Snickers (52g bar)", cal: 250, protein: 4, carbs: 33, fat: 12, fiber: 1, sugar: 27, serving: 1, unit: "bar", category: "processed" },
  { id: 335, name: "Mars Bar (51g)", cal: 228, protein: 3, carbs: 33, fat: 9, fiber: 0.5, sugar: 29, serving: 1, unit: "bar", category: "processed" },
  { id: 336, name: "Twix (50g bar)", cal: 250, protein: 2, carbs: 33, fat: 12, fiber: 0.5, sugar: 22, serving: 1, unit: "bar", category: "processed" },
  { id: 337, name: "Cadbury Dairy Milk (45g)", cal: 240, protein: 3, carbs: 28, fat: 13, fiber: 0.5, sugar: 26, serving: 1, unit: "bar", category: "processed" },
  { id: 338, name: "Nutella", cal: 539, protein: 6, carbs: 57, fat: 31, fiber: 3.5, sugar: 56, serving: 100, unit: "g", category: "processed" },
  { id: 339, name: "Maggi 2-Minute Noodles", cal: 295, protein: 7, carbs: 42, fat: 11, fiber: 2, sugar: 1, serving: 70, unit: "g", category: "processed" },
  { id: 340, name: "Indomie Instant Noodles", cal: 370, protein: 8, carbs: 52, fat: 14, fiber: 2, sugar: 2, serving: 85, unit: "g", category: "processed" },
  { id: 341, name: "Cup Noodles", cal: 291, protein: 7, carbs: 38, fat: 12, fiber: 1, sugar: 1, serving: 64, unit: "g", category: "processed" },
  { id: 342, name: "Knorr Chicken Noodles", cal: 345, protein: 9, carbs: 50, fat: 12, fiber: 1.5, sugar: 2, serving: 75, unit: "g", category: "processed" },
  { id: 343, name: "McDonald's Medium Fries", cal: 378, protein: 4, carbs: 48, fat: 19, fiber: 4, sugar: 0.5, serving: 1, unit: "serving", category: "fast food" },
  { id: 344, name: "McDonald's McChicken", cal: 400, protein: 14, carbs: 41, fat: 18, fiber: 2, sugar: 5, serving: 1, unit: "burger", category: "fast food" },
  { id: 345, name: "McDonald's McNuggets (6pcs)", cal: 280, protein: 15, carbs: 18, fat: 16, fiber: 0.5, sugar: 0.5, serving: 6, unit: "pieces", category: "fast food" },
  { id: 346, name: "KFC Original Fried Chicken (1pc)", cal: 350, protein: 39, carbs: 11, fat: 16, fiber: 0.3, sugar: 0.3, serving: 1, unit: "piece", category: "fast food" },
  { id: 347, name: "Burger King Whopper", cal: 657, protein: 28, carbs: 49, fat: 40, fiber: 2, sugar: 11, serving: 1, unit: "burger", category: "fast food" },
  { id: 348, name: "Subway 6\" Italian BMT", cal: 410, protein: 23, carbs: 44, fat: 16, fiber: 3, sugar: 6, serving: 1, unit: "sandwich", category: "fast food" },
  { id: 349, name: "Subway 6\" Chicken Teriyaki", cal: 380, protein: 26, carbs: 48, fat: 7, fiber: 3, sugar: 9, serving: 1, unit: "sandwich", category: "fast food" },
  { id: 350, name: "Dominos Pepperoni Pizza (1 slice)", cal: 299, protein: 13, carbs: 31, fat: 13, fiber: 1.5, sugar: 3, serving: 1, unit: "slice", category: "fast food" },
  { id: 351, name: "Pizza Hut Margherita (1 slice)", cal: 255, protein: 12, carbs: 33, fat: 8, fiber: 1.5, sugar: 3, serving: 1, unit: "slice", category: "fast food" },
  { id: 352, name: "Twinkies", cal: 270, protein: 2, carbs: 45, fat: 9, fiber: 0.5, sugar: 28, serving: 2, unit: "pieces", category: "processed" },
  { id: 353, name: "Pop-Tarts (1 pastry)", cal: 200, protein: 2.5, carbs: 38, fat: 5, fiber: 0.5, sugar: 16, serving: 1, unit: "pastry", category: "processed" },
  { id: 354, name: "Ritz Crackers", cal: 480, protein: 7, carbs: 62, fat: 23, fiber: 2, sugar: 7, serving: 100, unit: "g", category: "processed" },
  { id: 355, name: "Peanut M&Ms", cal: 517, protein: 11, carbs: 60, fat: 27, fiber: 3, sugar: 48, serving: 100, unit: "g", category: "processed" },
  { id: 356, name: "Reese's Peanut Butter Cup", cal: 513, protein: 11, carbs: 55, fat: 30, fiber: 2, sugar: 48, serving: 100, unit: "g", category: "processed" },
  { id: 357, name: "Haribo Gummy Bears", cal: 330, protein: 6, carbs: 77, fat: 0.5, fiber: 0, sugar: 46, serving: 100, unit: "g", category: "processed" },
  { id: 358, name: "Milka Chocolate Bar (100g)", cal: 525, protein: 7, carbs: 58, fat: 29, fiber: 1.5, sugar: 54, serving: 100, unit: "g", category: "processed" },

  // ══════════════════════════════════════════════════════════
  // 🇸🇦 / 🌍 MORE REGIONAL FOODS
  // ══════════════════════════════════════════════════════════
  { id: 359, name: "Harees (wheat & meat porridge)", cal: 180, protein: 12, carbs: 22, fat: 5, fiber: 1, sugar: 0.5, serving: 200, unit: "g", category: "arabic" },
  { id: 360, name: "Mutabbaq (stuffed pancake)", cal: 320, protein: 10, carbs: 38, fat: 14, fiber: 1, sugar: 2, serving: 1, unit: "piece", category: "arabic" },
  { id: 361, name: "Lentil Soup (Arabic-style)", cal: 90, protein: 6, carbs: 14, fat: 2, fiber: 4, sugar: 1, serving: 250, unit: "ml", category: "arabic" },
  { id: 362, name: "Chapli Kebab", cal: 165, protein: 14, carbs: 5, fat: 10, fiber: 0.5, sugar: 1, serving: 1, unit: "piece", category: "pakistani" },
  { id: 363, name: "Chicken Chargha (whole)", cal: 210, protein: 22, carbs: 4, fat: 12, fiber: 0.3, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 364, name: "Murgh Musallam", cal: 240, protein: 20, carbs: 6, fat: 15, fiber: 0.5, sugar: 2, serving: 100, unit: "g", category: "pakistani" },
  { id: 365, name: "Daal Gosht (lentil & meat)", cal: 145, protein: 11, carbs: 12, fat: 6, fiber: 3, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 366, name: "Aloo Keema", cal: 170, protein: 12, carbs: 10, fat: 9, fiber: 1.5, sugar: 1, serving: 100, unit: "g", category: "pakistani" },
  { id: 367, name: "Chicken Rolls (Pakistani)", cal: 280, protein: 14, carbs: 32, fat: 10, fiber: 1, sugar: 2, serving: 1, unit: "roll", category: "pakistani" },
  { id: 368, name: "Falooda", cal: 230, protein: 5, carbs: 40, fat: 6, fiber: 0.5, sugar: 28, serving: 350, unit: "ml", category: "pakistani" },
  { id: 369, name: "Rabdi Kheer", cal: 210, protein: 6, carbs: 28, fat: 8.5, fiber: 0, sugar: 22, serving: 150, unit: "g", category: "pakistani" },
  { id: 370, name: "Corn on the Cob (boiled)", cal: 96, protein: 3.4, carbs: 21, fat: 1.5, fiber: 2.4, sugar: 4.5, serving: 1, unit: "cob", category: "vegetables" },
  { id: 371, name: "Roasted Corn (desi style)", cal: 125, protein: 3.5, carbs: 24, fat: 2.5, fiber: 2.5, sugar: 4, serving: 1, unit: "cob", category: "pakistani" },
  { id: 372, name: "Bhatura", cal: 245, protein: 6, carbs: 36, fat: 9, fiber: 1.5, sugar: 0.5, serving: 1, unit: "piece", category: "indian" },
  { id: 373, name: "Pani Puri (6pcs + water)", cal: 195, protein: 4, carbs: 32, fat: 6, fiber: 2, sugar: 2, serving: 6, unit: "pieces", category: "indian" },
  { id: 374, name: "Dahi Vada", cal: 200, protein: 7, carbs: 26, fat: 8, fiber: 2, sugar: 7, serving: 150, unit: "g", category: "indian" },
  { id: 375, name: "Aloo Tikki", cal: 195, protein: 4, carbs: 28, fat: 8, fiber: 2.5, sugar: 1, serving: 2, unit: "pieces", category: "indian" },
  { id: 376, name: "Chaat Masala (seasoning)", cal: 270, protein: 10, carbs: 45, fat: 7, fiber: 8, sugar: 3, serving: 100, unit: "g", category: "indian" },
  { id: 377, name: "Lemon Rice (South Indian)", cal: 150, protein: 3, carbs: 30, fat: 3, fiber: 0.5, sugar: 0.5, serving: 100, unit: "g", category: "indian" },
  { id: 378, name: "Coconut Rice", cal: 180, protein: 3, carbs: 32, fat: 5, fiber: 1, sugar: 1, serving: 100, unit: "g", category: "indian" },
  { id: 379, name: "Bibinca (Goan dessert)", cal: 280, protein: 5, carbs: 40, fat: 11, fiber: 0.5, sugar: 28, serving: 100, unit: "g", category: "indian" },
  { id: 380, name: "Kaju Katli (cashew sweet)", cal: 490, protein: 10, carbs: 56, fat: 26, fiber: 1, sugar: 50, serving: 100, unit: "g", category: "indian" },
  { id: 381, name: "Chole Bhature", cal: 580, protein: 16, carbs: 78, fat: 22, fiber: 6, sugar: 3, serving: 1, unit: "serving", category: "indian" },
  { id: 382, name: "Missi Roti", cal: 190, protein: 7, carbs: 30, fat: 5.5, fiber: 4, sugar: 0.5, serving: 1, unit: "piece", category: "indian" },
  { id: 383, name: "Bombay Sandwich", cal: 320, protein: 9, carbs: 48, fat: 10, fiber: 3, sugar: 4, serving: 1, unit: "sandwich", category: "indian" },
  { id: 384, name: "Tinda (Indian round gourd)", cal: 21, protein: 1.4, carbs: 4, fat: 0.2, fiber: 1.6, sugar: 2, serving: 100, unit: "g", category: "vegetables" },
  { id: 385, name: "Karela (bitter gourd)", cal: 17, protein: 1, carbs: 3.7, fat: 0.2, fiber: 2.8, sugar: 1.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 386, name: "Bhindi (okra, cooked)", cal: 33, protein: 1.9, carbs: 7, fat: 0.2, fiber: 3.2, sugar: 1.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 387, name: "Methi (fenugreek leaves)", cal: 49, protein: 4.4, carbs: 6, fat: 0.9, fiber: 3.7, sugar: 0.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 388, name: "Lauki (bottle gourd)", cal: 15, protein: 0.7, carbs: 3.4, fat: 0.1, fiber: 1.2, sugar: 1.8, serving: 100, unit: "g", category: "vegetables" },
  { id: 389, name: "Arbi (taro root)", cal: 112, protein: 1.5, carbs: 26, fat: 0.2, fiber: 4.1, sugar: 0.5, serving: 100, unit: "g", category: "vegetables" },
  { id: 390, name: "Besan (chickpea flour)", cal: 387, protein: 22, carbs: 58, fat: 6, fiber: 10, sugar: 11, serving: 100, unit: "g", category: "grains" },

  // ══════════════════════════════════════════════════════════
  // 🥤 BEVERAGES
  // ══════════════════════════════════════════════════════════
  { id: 391, name: "Whole Milk (full fat)", cal: 61, protein: 3.2, carbs: 4.8, fat: 3.3, fiber: 0, sugar: 5, serving: 100, unit: "ml", category: "beverages" },
  { id: 392, name: "Skim Milk (0% fat)", cal: 35, protein: 3.4, carbs: 5, fat: 0.1, fiber: 0, sugar: 5, serving: 100, unit: "ml", category: "beverages" },
  { id: 393, name: "Orange Juice (fresh)", cal: 45, protein: 0.7, carbs: 10, fat: 0.2, fiber: 0.2, sugar: 8.4, serving: 100, unit: "ml", category: "beverages" },
  { id: 394, name: "Apple Juice", cal: 47, protein: 0.1, carbs: 11, fat: 0.1, fiber: 0, sugar: 10, serving: 100, unit: "ml", category: "beverages" },
  { id: 395, name: "Mango Juice (packaged)", cal: 65, protein: 0.3, carbs: 16, fat: 0.1, fiber: 0.3, sugar: 14, serving: 100, unit: "ml", category: "beverages" },
  { id: 396, name: "Black Tea (no sugar)", cal: 2, protein: 0, carbs: 0.5, fat: 0, fiber: 0, sugar: 0, serving: 240, unit: "ml", category: "beverages" },
  { id: 397, name: "Chai / Milk Tea (with sugar)", cal: 55, protein: 2, carbs: 7, fat: 2, fiber: 0, sugar: 6, serving: 240, unit: "ml", category: "beverages" },
  { id: 398, name: "Green Tea (unsweetened)", cal: 2, protein: 0.2, carbs: 0.5, fat: 0, fiber: 0, sugar: 0, serving: 240, unit: "ml", category: "beverages" },
  { id: 399, name: "Americano Coffee (black)", cal: 5, protein: 0.3, carbs: 1, fat: 0, fiber: 0, sugar: 0, serving: 240, unit: "ml", category: "beverages" },
  { id: 400, name: "Cappuccino (whole milk)", cal: 74, protein: 4, carbs: 7, fat: 3, fiber: 0, sugar: 6, serving: 240, unit: "ml", category: "beverages" },
  { id: 401, name: "Latte (whole milk)", cal: 120, protein: 6, carbs: 12, fat: 5, fiber: 0, sugar: 10, serving: 360, unit: "ml", category: "beverages" },
  { id: 402, name: "Tang Orange Powder Drink (made up)", cal: 50, protein: 0, carbs: 13, fat: 0, fiber: 0, sugar: 13, serving: 250, unit: "ml", category: "beverages" },
  { id: 403, name: "Rooh Afza Sherbet (diluted)", cal: 72, protein: 0, carbs: 18, fat: 0, fiber: 0, sugar: 18, serving: 250, unit: "ml", category: "beverages" },
  { id: 404, name: "Coconut Water (fresh)", cal: 19, protein: 0.7, carbs: 3.7, fat: 0.2, fiber: 1, sugar: 2.6, serving: 240, unit: "ml", category: "beverages" },
  { id: 405, name: "Lemonade (homemade, sweetened)", cal: 40, protein: 0, carbs: 10, fat: 0, fiber: 0, sugar: 10, serving: 240, unit: "ml", category: "beverages" },
  { id: 406, name: "Almond Milk (unsweetened)", cal: 13, protein: 0.4, carbs: 0.6, fat: 1.1, fiber: 0.2, sugar: 0, serving: 100, unit: "ml", category: "beverages" },
  { id: 407, name: "Protein Shake (whey, made up)", cal: 160, protein: 28, carbs: 8, fat: 2.5, fiber: 0.5, sugar: 4, serving: 350, unit: "ml", category: "beverages" },
  { id: 408, name: "Lassi (sweet, whole milk)", cal: 85, protein: 4, carbs: 11, fat: 3, fiber: 0, sugar: 10, serving: 200, unit: "ml", category: "beverages" },
  { id: 409, name: "Lassi (salty, dhahi)", cal: 60, protein: 4, carbs: 6, fat: 2.5, fiber: 0, sugar: 4, serving: 200, unit: "ml", category: "beverages" },

  // ══════════════════════════════════════════════════════════
  // 🫙 FATS & OILS
  // ══════════════════════════════════════════════════════════
  { id: 410, name: "Olive Oil (extra virgin)", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 411, name: "Coconut Oil", cal: 862, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 412, name: "Ghee (clarified butter)", cal: 900, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "g", category: "fats" },
  { id: 413, name: "Butter (unsalted)", cal: 717, protein: 0.9, carbs: 0.1, fat: 81, fiber: 0, sugar: 0.1, serving: 100, unit: "g", category: "fats" },
  { id: 414, name: "Avocado Oil", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 415, name: "Sunflower Oil", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 416, name: "Canola Oil", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 417, name: "Sesame Oil (toasted)", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },
  { id: 418, name: "Peanut Oil", cal: 884, protein: 0, carbs: 0, fat: 100, fiber: 0, sugar: 0, serving: 100, unit: "ml", category: "fats" },

  // ══════════════════════════════════════════════════════════
  // 🇬🇧 BRITISH FOODS
  // ══════════════════════════════════════════════════════════
  { id: 419, name: "Fish and Chips (takeaway)", cal: 900, protein: 28, carbs: 90, fat: 50, fiber: 4, sugar: 2, serving: 1, unit: "serving", category: "british" },
  { id: 420, name: "Full English Breakfast", cal: 807, protein: 42, carbs: 37, fat: 55, fiber: 4, sugar: 5, serving: 1, unit: "plate", category: "british" },
  { id: 421, name: "Baked Beans on Toast", cal: 285, protein: 14, carbs: 47, fat: 4, fiber: 8, sugar: 9, serving: 1, unit: "serving", category: "british" },
  { id: 422, name: "Shepherd's Pie", cal: 135, protein: 10, carbs: 14, fat: 5, fiber: 2, sugar: 2, serving: 100, unit: "g", category: "british" },
  { id: 423, name: "Chicken Tikka Masala (British version)", cal: 160, protein: 15, carbs: 8, fat: 8, fiber: 1, sugar: 4, serving: 100, unit: "g", category: "british" },
  { id: 424, name: "Cornish Pasty", cal: 300, protein: 10, carbs: 32, fat: 15, fiber: 2, sugar: 2, serving: 1, unit: "piece", category: "british" },
  { id: 425, name: "Scone with Cream & Jam", cal: 320, protein: 5, carbs: 45, fat: 14, fiber: 1, sugar: 20, serving: 1, unit: "scone", category: "british" },
  { id: 426, name: "Bangers and Mash", cal: 350, protein: 16, carbs: 30, fat: 18, fiber: 3, sugar: 2, serving: 1, unit: "serving", category: "british" },
  { id: 427, name: "Sticky Toffee Pudding", cal: 420, protein: 5, carbs: 62, fat: 18, fiber: 1, sugar: 48, serving: 1, unit: "serving", category: "british" },
  { id: 428, name: "Yorkshire Pudding", cal: 165, protein: 5, carbs: 19, fat: 8, fiber: 0.5, sugar: 1, serving: 1, unit: "pudding", category: "british" },

  // ══════════════════════════════════════════════════════════
  // 🇸🇬 SINGAPOREAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 429, name: "Chicken Rice (Hainanese)", cal: 607, protein: 35, carbs: 65, fat: 22, fiber: 1.5, sugar: 2, serving: 1, unit: "plate", category: "singaporean" },
  { id: 430, name: "Laksa (Singapore)", cal: 395, protein: 18, carbs: 45, fat: 15, fiber: 3, sugar: 4, serving: 1, unit: "bowl", category: "singaporean" },
  { id: 431, name: "Char Kway Teow", cal: 743, protein: 25, carbs: 75, fat: 38, fiber: 3, sugar: 4, serving: 1, unit: "plate", category: "singaporean" },
  { id: 432, name: "Chili Crab (with mantou)", cal: 430, protein: 28, carbs: 30, fat: 18, fiber: 2, sugar: 8, serving: 1, unit: "serving", category: "singaporean" },
  { id: 433, name: "Nasi Lemak (with chicken)", cal: 644, protein: 30, carbs: 70, fat: 28, fiber: 4, sugar: 5, serving: 1, unit: "plate", category: "singaporean" },
  { id: 434, name: "Kaya Toast with Soft Eggs", cal: 380, protein: 14, carbs: 42, fat: 18, fiber: 1, sugar: 12, serving: 1, unit: "set", category: "singaporean" },
  { id: 435, name: "Rojak (fruit & vegetable salad)", cal: 220, protein: 5, carbs: 35, fat: 7, fiber: 4, sugar: 20, serving: 1, unit: "serving", category: "singaporean" },
  { id: 436, name: "Roti Prata (with curry)", cal: 400, protein: 12, carbs: 55, fat: 16, fiber: 3, sugar: 2, serving: 2, unit: "pieces", category: "singaporean" },
  { id: 437, name: "Ice Kacang (ABC)", cal: 265, protein: 3, carbs: 60, fat: 1, fiber: 2, sugar: 48, serving: 1, unit: "serving", category: "singaporean" },

  // ══════════════════════════════════════════════════════════
  // 🇻🇳 VIETNAMESE FOODS
  // ══════════════════════════════════════════════════════════
  { id: 438, name: "Pho Bo (beef noodle soup)", cal: 364, protein: 25, carbs: 45, fat: 8, fiber: 2, sugar: 3, serving: 1, unit: "bowl", category: "vietnamese" },
  { id: 439, name: "Banh Mi (pork, full)", cal: 490, protein: 24, carbs: 60, fat: 18, fiber: 3, sugar: 5, serving: 1, unit: "sandwich", category: "vietnamese" },
  { id: 440, name: "Goi Cuon (summer rolls, 2pcs)", cal: 200, protein: 10, carbs: 30, fat: 4, fiber: 2, sugar: 3, serving: 2, unit: "rolls", category: "vietnamese" },
  { id: 441, name: "Bun Bo Hue (spicy beef noodle)", cal: 420, protein: 28, carbs: 50, fat: 10, fiber: 2, sugar: 3, serving: 1, unit: "bowl", category: "vietnamese" },
  { id: 442, name: "Com Tam (broken rice with pork)", cal: 620, protein: 35, carbs: 70, fat: 22, fiber: 2, sugar: 4, serving: 1, unit: "plate", category: "vietnamese" },
  { id: 443, name: "Banh Xeo (sizzling crepe)", cal: 380, protein: 18, carbs: 40, fat: 16, fiber: 3, sugar: 3, serving: 1, unit: "crepe", category: "vietnamese" },
  { id: 444, name: "Vietnamese Iced Coffee (ca phe)", cal: 150, protein: 2, carbs: 24, fat: 4, fiber: 0, sugar: 22, serving: 1, unit: "glass", category: "vietnamese" },
  { id: 445, name: "Che (sweet dessert soup)", cal: 180, protein: 3, carbs: 38, fat: 2, fiber: 3, sugar: 28, serving: 1, unit: "bowl", category: "vietnamese" },

  // ══════════════════════════════════════════════════════════
  // 🇫🇷 FRENCH FOODS
  // ══════════════════════════════════════════════════════════
  { id: 446, name: "Croissant (plain)", cal: 406, protein: 8, carbs: 45, fat: 21, fiber: 2, sugar: 8, serving: 100, unit: "g", category: "french" },
  { id: 447, name: "Pain au Chocolat", cal: 420, protein: 7, carbs: 48, fat: 22, fiber: 2, sugar: 14, serving: 1, unit: "piece", category: "french" },
  { id: 448, name: "Crêpe (plain, thin)", cal: 103, protein: 3, carbs: 15, fat: 4, fiber: 0.5, sugar: 2, serving: 1, unit: "crepe", category: "french" },
  { id: 449, name: "Quiche Lorraine (slice)", cal: 370, protein: 12, carbs: 25, fat: 25, fiber: 1, sugar: 3, serving: 1, unit: "slice", category: "french" },
  { id: 450, name: "Ratatouille", cal: 75, protein: 2, carbs: 10, fat: 3, fiber: 3, sugar: 5, serving: 200, unit: "g", category: "french" },
  { id: 451, name: "Croque Monsieur", cal: 450, protein: 22, carbs: 38, fat: 23, fiber: 2, sugar: 4, serving: 1, unit: "sandwich", category: "french" },
  { id: 452, name: "French Onion Soup", cal: 240, protein: 9, carbs: 30, fat: 9, fiber: 2, sugar: 8, serving: 1, unit: "bowl", category: "french" },
  { id: 453, name: "Coq au Vin", cal: 175, protein: 20, carbs: 6, fat: 8, fiber: 1, sugar: 2, serving: 200, unit: "g", category: "french" },
  { id: 454, name: "Crème Brûlée", cal: 350, protein: 5, carbs: 32, fat: 22, fiber: 0, sugar: 28, serving: 1, unit: "ramekin", category: "french" },

  // ══════════════════════════════════════════════════════════
  // 🇪🇺 EUROPEAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 455, name: "Wiener Schnitzel (breaded veal)", cal: 260, protein: 26, carbs: 12, fat: 12, fiber: 0.5, sugar: 0.5, serving: 150, unit: "g", category: "european" },
  { id: 456, name: "Pierogi (potato & cheese, boiled)", cal: 190, protein: 6, carbs: 30, fat: 5, fiber: 1, sugar: 1, serving: 4, unit: "pieces", category: "european" },
  { id: 457, name: "Goulash (Hungarian beef stew)", cal: 140, protein: 14, carbs: 8, fat: 6, fiber: 1.5, sugar: 3, serving: 200, unit: "g", category: "european" },
  { id: 458, name: "Bratwurst (grilled)", cal: 259, protein: 14, carbs: 2, fat: 22, fiber: 0, sugar: 0.5, serving: 85, unit: "g", category: "european" },
  { id: 459, name: "Borscht (beetroot soup)", cal: 60, protein: 2, carbs: 12, fat: 0.5, fiber: 2, sugar: 7, serving: 250, unit: "ml", category: "european" },
  { id: 460, name: "Stroganoff (beef, with noodles)", cal: 215, protein: 16, carbs: 18, fat: 8, fiber: 1, sugar: 2, serving: 200, unit: "g", category: "european" },
  { id: 461, name: "Tiramisu", cal: 280, protein: 5, carbs: 30, fat: 16, fiber: 0.5, sugar: 22, serving: 100, unit: "g", category: "european" },
  { id: 462, name: "Apple Strudel", cal: 280, protein: 4, carbs: 40, fat: 12, fiber: 2, sugar: 22, serving: 100, unit: "g", category: "european" },

  // ══════════════════════════════════════════════════════════
  // 🇮🇩 INDONESIAN FOODS
  // ══════════════════════════════════════════════════════════
  { id: 463, name: "Beef Rendang", cal: 195, protein: 18, carbs: 5, fat: 12, fiber: 1, sugar: 2, serving: 100, unit: "g", category: "indonesian" },
  { id: 464, name: "Chicken Satay (3 skewers + sauce)", cal: 370, protein: 32, carbs: 22, fat: 18, fiber: 2, sugar: 8, serving: 3, unit: "skewers", category: "indonesian" },
  { id: 465, name: "Gado Gado (peanut sauce salad)", cal: 280, protein: 12, carbs: 28, fat: 14, fiber: 5, sugar: 8, serving: 1, unit: "serving", category: "indonesian" },
  { id: 466, name: "Nasi Goreng (fried rice)", cal: 340, protein: 12, carbs: 48, fat: 12, fiber: 2, sugar: 3, serving: 1, unit: "plate", category: "indonesian" },
  { id: 467, name: "Soto Ayam (chicken soup)", cal: 180, protein: 16, carbs: 14, fat: 6, fiber: 1.5, sugar: 2, serving: 1, unit: "bowl", category: "indonesian" },
  { id: 468, name: "Tempeh (fermented soy, raw)", cal: 193, protein: 19, carbs: 9, fat: 11, fiber: 9, sugar: 0, serving: 100, unit: "g", category: "indonesian" },
  { id: 469, name: "Bakso (meatball soup)", cal: 270, protein: 18, carbs: 28, fat: 9, fiber: 1, sugar: 2, serving: 1, unit: "bowl", category: "indonesian" },
  { id: 470, name: "Es Teler (fruit dessert drink)", cal: 195, protein: 2, carbs: 40, fat: 4, fiber: 2, sugar: 32, serving: 1, unit: "glass", category: "indonesian" },

  // ══════════════════════════════════════════════════════════
  // 🇹🇭 THAI FOODS
  // ══════════════════════════════════════════════════════════
  { id: 471, name: "Pad Thai (chicken)", cal: 350, protein: 22, carbs: 42, fat: 10, fiber: 2, sugar: 8, serving: 1, unit: "plate", category: "thai" },
  { id: 472, name: "Tom Yum Soup (shrimp)", cal: 120, protein: 12, carbs: 8, fat: 4, fiber: 2, sugar: 3, serving: 1, unit: "bowl", category: "thai" },
  { id: 473, name: "Massaman Curry (beef)", cal: 180, protein: 14, carbs: 12, fat: 9, fiber: 2, sugar: 5, serving: 200, unit: "g", category: "thai" },
  { id: 474, name: "Mango Sticky Rice", cal: 330, protein: 5, carbs: 62, fat: 7, fiber: 3, sugar: 30, serving: 1, unit: "serving", category: "thai" },
  { id: 475, name: "Pad See Ew (flat noodles)", cal: 390, protein: 18, carbs: 55, fat: 12, fiber: 2, sugar: 6, serving: 1, unit: "plate", category: "thai" },
  { id: 476, name: "Som Tum (green papaya salad)", cal: 95, protein: 3, carbs: 18, fat: 1, fiber: 3, sugar: 10, serving: 1, unit: "serving", category: "thai" },
  { id: 477, name: "Thai Basil Chicken (Pad Kra Pao)", cal: 295, protein: 25, carbs: 12, fat: 15, fiber: 1, sugar: 4, serving: 1, unit: "serving", category: "thai" },
  { id: 478, name: "Tom Kha Gai (coconut chicken soup)", cal: 190, protein: 14, carbs: 6, fat: 13, fiber: 1.5, sugar: 3, serving: 1, unit: "bowl", category: "thai" },

  // ══════════════════════════════════════════════════════════
  // 🍿 SNACKS
  // ══════════════════════════════════════════════════════════
  { id: 479, name: "Popcorn (air-popped)", cal: 387, protein: 13, carbs: 78, fat: 4.5, fiber: 15, sugar: 0.9, serving: 100, unit: "g", category: "snacks" },
  { id: 480, name: "Rice Cakes (plain)", cal: 387, protein: 8, carbs: 80, fat: 2.8, fiber: 1.5, sugar: 0.5, serving: 100, unit: "g", category: "snacks" },
  { id: 481, name: "Granola Bar (oats & honey)", cal: 420, protein: 8, carbs: 64, fat: 14, fiber: 4, sugar: 28, serving: 100, unit: "g", category: "snacks" },
  { id: 482, name: "Protein Bar (generic)", cal: 350, protein: 20, carbs: 40, fat: 10, fiber: 5, sugar: 18, serving: 100, unit: "g", category: "snacks" },
  { id: 483, name: "Hummus with Pita (single serve)", cal: 265, protein: 8, carbs: 35, fat: 10, fiber: 5, sugar: 2, serving: 1, unit: "serving", category: "snacks" },
  { id: 484, name: "Chex Mix (snack mix)", cal: 433, protein: 10, carbs: 63, fat: 17, fiber: 3, sugar: 6, serving: 100, unit: "g", category: "snacks" },
  { id: 485, name: "Trail Mix (nuts & dried fruit)", cal: 462, protein: 11, carbs: 50, fat: 26, fiber: 5, sugar: 28, serving: 100, unit: "g", category: "snacks" },
  { id: 486, name: "Banana Chips (dried)", cal: 520, protein: 2, carbs: 58, fat: 33, fiber: 5, sugar: 35, serving: 100, unit: "g", category: "snacks" },
  { id: 487, name: "Nachos with Salsa", cal: 380, protein: 7, carbs: 52, fat: 18, fiber: 3, sugar: 5, serving: 1, unit: "serving", category: "snacks" },

  // ══════════════════════════════════════════════════════════
  // 🌏 MORE WORLD FOODS
  // ══════════════════════════════════════════════════════════
  { id: 488, name: "Falafel (3 pieces)", cal: 333, protein: 13, carbs: 32, fat: 18, fiber: 6, sugar: 2, serving: 3, unit: "pieces", category: "arabic" },
  { id: 489, name: "Kibbeh (baked)", cal: 215, protein: 12, carbs: 16, fat: 11, fiber: 1, sugar: 0.5, serving: 100, unit: "g", category: "arabic" },
  { id: 490, name: "Fatteh (Lebanese bread dish)", cal: 370, protein: 18, carbs: 42, fat: 14, fiber: 5, sugar: 5, serving: 1, unit: "serving", category: "arabic" },
  { id: 491, name: "Maqluba (Palestinian upside-down rice)", cal: 250, protein: 14, carbs: 32, fat: 8, fiber: 2, sugar: 1, serving: 200, unit: "g", category: "arabic" },
  { id: 492, name: "Spaghetti Carbonara", cal: 465, protein: 19, carbs: 55, fat: 18, fiber: 3, sugar: 2, serving: 1, unit: "plate", category: "italian" },
  { id: 493, name: "Chicken Parmigiana", cal: 350, protein: 30, carbs: 22, fat: 15, fiber: 2, sugar: 4, serving: 1, unit: "serving", category: "italian" },
  { id: 494, name: "Gelato (vanilla)", cal: 168, protein: 4, carbs: 24, fat: 7, fiber: 0, sugar: 22, serving: 100, unit: "g", category: "italian" },
  { id: 495, name: "Galbi (Korean short ribs, grilled)", cal: 330, protein: 25, carbs: 12, fat: 21, fiber: 0.5, sugar: 10, serving: 150, unit: "g", category: "korean" },
  { id: 496, name: "Japchae (glass noodles with veg)", cal: 180, protein: 5, carbs: 30, fat: 5, fiber: 2, sugar: 4, serving: 150, unit: "g", category: "korean" },
  { id: 497, name: "Soondubu Jjigae (soft tofu stew)", cal: 165, protein: 12, carbs: 8, fat: 8, fiber: 2, sugar: 2, serving: 1, unit: "bowl", category: "korean" },
  { id: 498, name: "Tacos (beef, 2 pcs)", cal: 380, protein: 22, carbs: 32, fat: 18, fiber: 4, sugar: 4, serving: 2, unit: "tacos", category: "mexican" },
  { id: 499, name: "Enchiladas (chicken, 2 pcs)", cal: 440, protein: 28, carbs: 42, fat: 16, fiber: 4, sugar: 5, serving: 2, unit: "enchiladas", category: "mexican" },
  { id: 500, name: "Churros (with chocolate dip)", cal: 480, protein: 6, carbs: 58, fat: 25, fiber: 2, sugar: 22, serving: 100, unit: "g", category: "mexican" },
];

const QUICK_EXERCISES = [
  { name: "Running (moderate)", calPerMin: 11, type: "cardio", icon: "🏃" },
  { name: "Walking", calPerMin: 5, type: "cardio", icon: "🚶" },
  { name: "Cycling", calPerMin: 10, type: "cardio", icon: "🚴" },
  { name: "Swimming", calPerMin: 10, type: "cardio", icon: "🏊" },
  { name: "Jump Rope", calPerMin: 13, type: "cardio", icon: "⚡" },
  { name: "Weight Training", calPerMin: 7, type: "strength", icon: "🏋️" },
  { name: "HIIT Workout", calPerMin: 12, type: "cardio", icon: "🔥" },
  { name: "Yoga", calPerMin: 4, type: "flexibility", icon: "🧘" },
  { name: "Pilates", calPerMin: 5, type: "flexibility", icon: "🤸" },
  { name: "Basketball", calPerMin: 9, type: "sports", icon: "🏀" },
  { name: "Soccer / Football", calPerMin: 9, type: "sports", icon: "⚽" },
  { name: "Tennis", calPerMin: 8, type: "sports", icon: "🎾" },
  { name: "Elliptical", calPerMin: 9, type: "cardio", icon: "🔄" },
  { name: "Rowing Machine", calPerMin: 10, type: "cardio", icon: "🚣" },
  { name: "Push-ups", calPerMin: 6, type: "strength", icon: "💪" },
  { name: "Cricket", calPerMin: 5, type: "sports", icon: "🏏" },
  { name: "Badminton", calPerMin: 7, type: "sports", icon: "🏸" },
  { name: "Dancing", calPerMin: 6, type: "cardio", icon: "💃" },
  { name: "Stair Climbing", calPerMin: 9, type: "cardio", icon: "🪜" },
  { name: "Treadmill (incline)", calPerMin: 10, type: "cardio", icon: "🏃" },
];

const ACHIEVEMENTS = [
  { id: "first_log", name: "First Step", desc: "Log your first food", icon: "🌱", xp: 10, type: "milestone" },
  { id: "streak_3", name: "Hot Streak", desc: "Log 3 days in a row", icon: "🔥", xp: 30, type: "streak" },
  { id: "streak_7", name: "Week Warrior", desc: "Log 7 days in a row", icon: "⚡", xp: 70, type: "streak" },
  { id: "streak_30", name: "Monthly Master", desc: "Log 30 days in a row", icon: "🏆", xp: 300, type: "streak" },
  { id: "goal_met", name: "On Target", desc: "Meet your calorie goal", icon: "🎯", xp: 20, type: "goal" },
  { id: "goal_met_5", name: "Consistent", desc: "Meet goal 5 times", icon: "✅", xp: 100, type: "goal" },
  { id: "water_goal", name: "Hydrated", desc: "Reach water goal", icon: "💧", xp: 15, type: "health" },
  { id: "protein_goal", name: "Protein Power", desc: "Hit protein goal", icon: "💪", xp: 20, type: "nutrition" },
  { id: "exercise_1", name: "Active Day", desc: "Log your first exercise", icon: "🏃", xp: 25, type: "exercise" },
  { id: "exercise_10", name: "Fitness Fan", desc: "Log 10 exercises", icon: "🎽", xp: 150, type: "exercise" },
  { id: "weight_logged", name: "Scale Watcher", desc: "Log your weight", icon: "⚖️", xp: 10, type: "health" },
  { id: "recipe_created", name: "Chef's Kiss", desc: "Create a recipe", icon: "👨‍🍳", xp: 30, type: "food" },
  { id: "custom_food", name: "Foodie", desc: "Add a custom food", icon: "🥘", xp: 20, type: "food" },
  { id: "fasting_done", name: "Fast & Furious", desc: "Complete a fast", icon: "⏰", xp: 40, type: "health" },
  { id: "calorie_under", name: "Discipline King", desc: "Stay under calories", icon: "👑", xp: 25, type: "goal" },
  { id: "all_macros", name: "Macro Master", desc: "Hit all macro goals", icon: "🌟", xp: 50, type: "nutrition" },
  { id: "foods_50", name: "Explorer", desc: "Log 50 different foods", icon: "🗺️", xp: 100, type: "food" },
  { id: "xp_500", name: "Rising Star", desc: "Earn 500 XP total", icon: "⭐", xp: 50, type: "milestone" },
  { id: "xp_1000", name: "NutriFlow Pro", desc: "Earn 1000 XP total", icon: "💫", xp: 100, type: "milestone" },
  { id: "perfect_day", name: "Perfect Day", desc: "Hit all daily goals", icon: "🌈", xp: 75, type: "milestone" },
];

const AI_MEAL_SUGGESTIONS = {
  highProtein: [
    { name: "Chicken Tikka + Chapati", foods: ["Chicken Tikka", "Chapati", "Raita"], cal: 380, protein: 32, emoji: "🍗" },
    { name: "Desi Protein Bowl", foods: ["Chicken Breast", "Brown Rice", "Dal Tadka"], cal: 450, protein: 45, emoji: "🥣" },
    { name: "Egg Paratha Combo", foods: ["Aloo Paratha", "Eggs", "Yogurt"], cal: 480, protein: 22, emoji: "🍳" },
    { name: "Greek Yogurt Bowl", foods: ["Greek Yogurt", "Blueberries", "Almonds"], cal: 280, protein: 22, emoji: "🫐" },
    { name: "Tuna Salad", foods: ["Tuna", "Spinach", "Cucumber"], cal: 200, protein: 30, emoji: "🥗" },
  ],
  balanced: [
    { name: "Chicken Biryani Meal", foods: ["Chicken Biryani", "Raita", "Salad"], cal: 520, protein: 28, emoji: "🍛" },
    { name: "Shawarma Wrap", foods: ["Chicken Shawarma", "Fattoush Salad"], cal: 450, protein: 27, emoji: "🌯" },
    { name: "Salmon & Quinoa", foods: ["Salmon Fillet", "Quinoa", "Broccoli"], cal: 480, protein: 36, emoji: "🐟" },
    { name: "Dal Chawal", foods: ["Masoor Dal", "White Rice", "Raita"], cal: 400, protein: 16, emoji: "🍚" },
    { name: "Korean Bibimbap", foods: ["Bibimbap", "Kimchi"], cal: 575, protein: 23, emoji: "🇰🇷" },
  ],
  lowCal: [
    { name: "Veggie Stir Fry", foods: ["Broccoli", "Zucchini", "Mushrooms"], cal: 120, protein: 6, emoji: "🥦" },
    { name: "Light Desi Salad", foods: ["Tomato", "Cucumber", "Spinach", "Lemon"], cal: 60, protein: 3, emoji: "🥗" },
    { name: "Tom Yum Soup", foods: ["Tom Yum Soup", "Tofu", "Mushrooms"], cal: 150, protein: 8, emoji: "🍲" },
    { name: "Miso + Edamame", foods: ["Miso Soup", "Edamame", "Soba Noodles"], cal: 260, protein: 16, emoji: "🇯🇵" },
  ],
  highCarb: [
    { name: "Halwa Puri Breakfast", foods: ["Halwa Puri", "Chai"], cal: 705, protein: 14, emoji: "🍽️" },
    { name: "Pasta Primavera", foods: ["Pasta", "Broccoli", "Tomato"], cal: 520, protein: 18, emoji: "🍝" },
    { name: "Banana Oatmeal", foods: ["Oatmeal", "Banana", "Honey"], cal: 380, protein: 8, emoji: "🍌" },
    { name: "Pad Thai Meal", foods: ["Pad Thai", "Spring Rolls"], cal: 610, protein: 25, emoji: "🇹🇭" },
  ],
};
